AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myHttpEndpoint:
    Type: String
    Default: !Ref 'myHttpEndpoint'
  OperatorEmail:
    Description: Email address to notify when new logs are published.
    Type: String
    Default: !Ref 'OperatorEmail'
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref 'OperatorEmail'
          Protocol: email
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: Topic
        resource_type: AWS::SNS::Topic
        file_path: /tmp/tmppo4czohi/sns/sns.yaml
        prancer_unique_id: efbf77e3-7d9e-43a9-9a24-aa123015be4d
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref 'Topic'
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
              AWS: '*'
            Resource: '*'
            Action: SNS:Publish
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: TopicPolicy
        resource_type: AWS::SNS::TopicPolicy
        file_path: /tmp/tmppo4czohi/sns/sns.yaml
        prancer_unique_id: 6760397a-d77f-4188-9468-1abb6c941db4
  SCMSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref 'Topic'
      Endpoint: !Ref 'myHttpEndpoint'
      Protocol: http
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 20
          minDelayTarget: 10
          maxDelayTarget: 30
          numMinDelayRetries: 3
          numMaxDelayRetries: 17
          numNoDelayRetries: 0
          backoffFunction: exponential
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: SCMSubscription
        resource_type: AWS::SNS::Subscription
        file_path: /tmp/tmppo4czohi/sns/sns.yaml
        prancer_unique_id: 9a06e1ac-10de-46ac-8da9-3266b3ce433e
