AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myHttpEndpoint:
    Type: String
    Default: !Ref 'myHttpEndpoint'
  OperatorEmail:
    Description: Email address to notify when new logs are published.
    Type: String
    Default: !Ref 'OperatorEmail'
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref 'OperatorEmail'
          Protocol: email
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: Topic
          resource_type: AWS::SNS::Topic
          file_path: sns/sns.yaml
          prancer_unique_id: 85f46ea7-f678-403a-858c-e237da5e5240
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref 'Topic'
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
              AWS: '*'
            Resource: '*'
            Action: SNS:Publish
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: TopicPolicy
          resource_type: AWS::SNS::TopicPolicy
          file_path: sns/sns.yaml
          prancer_unique_id: 18b57c4c-523e-4bd4-bf4a-c573973fd0f3
  SCMSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref 'Topic'
      Endpoint: !Ref 'myHttpEndpoint'
      Protocol: http
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 20
          minDelayTarget: 10
          maxDelayTarget: 30
          numMinDelayRetries: 3
          numMaxDelayRetries: 17
          numNoDelayRetries: 0
          backoffFunction: exponential
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: SCMSubscription
          resource_type: AWS::SNS::Subscription
          file_path: sns/sns.yaml
          prancer_unique_id: a0d0efec-cdd3-425f-a3d1-313ed50e1bc8
