AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myHttpEndpoint:
    Type: String
    Default: !Ref 'myHttpEndpoint'
  OperatorEmail:
    Description: Email address to notify when new logs are published.
    Type: String
    Default: !Ref 'OperatorEmail'
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref 'OperatorEmail'
          Protocol: email
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: Topic
          resource_type: AWS::SNS::Topic
          file_path: sns/sns.yaml
          prancer_unique_id: 1f1d9bb6-81d6-4297-9226-d7517dda5823
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref 'Topic'
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
              AWS: '*'
            Resource: '*'
            Action: SNS:Publish
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: TopicPolicy
          resource_type: AWS::SNS::TopicPolicy
          file_path: sns/sns.yaml
          prancer_unique_id: '06e3d6c2-7021-46a2-b62a-7f562058247c'
  SCMSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref 'Topic'
      Endpoint: !Ref 'myHttpEndpoint'
      Protocol: http
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 20
          minDelayTarget: 10
          maxDelayTarget: 30
          numMinDelayRetries: 3
          numMaxDelayRetries: 17
          numNoDelayRetries: 0
          backoffFunction: exponential
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: SCMSubscription
          resource_type: AWS::SNS::Subscription
          file_path: sns/sns.yaml
          prancer_unique_id: b01cbde0-3037-4c7f-a55c-a6700939493c
