AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SyntheticsCanary:
    Type: AWS::Synthetics::Canary
    Properties:
      Name: samplecanary
      ExecutionRoleArn: arn:aws:iam::123456789012:role/my-lambda-execution-role-to-run-canary
      Code:
        Handler: pageLoadBlueprint.handler
        Script: |
          var synthetics = require('Synthetics');
          const log = require('SyntheticsLogger');
          const pageLoadBlueprint = async function () {
          // INSERT URL here
          const URL = "https://amazon.com";

          let page = await synthetics.getPage();
          const response = await page.goto(URL, {waitUntil: 'domcontentloaded', timeout: 30000});
          //Wait for page to render.
          //Increase or decrease wait time based on endpoint being monitored.
          await page.waitFor(15000);
          await synthetics.takeScreenshot('loaded', 'loaded');
          let pageTitle = await page.title();
          log.info('Page title: ' + pageTitle);
          if (response.status() !== 200) {
               throw "Failed to load page!";
          }
          };

          exports.handler = async () => {
          return await pageLoadBlueprint();
          };
      ArtifactS3Location: ''
      RuntimeVersion: syn-1.0
      Schedule:
        Expression: rate(1 minute)
        DurationInSeconds: 3600
      RunConfig:
        TimeoutInSeconds: 60
      FailureRetentionPeriod: 30
      SuccessRetentionPeriod: 30
      Tags:
        - Key: key00AtCreate
          Value: value001AtCreate
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: SyntheticsCanary
          resource_type: AWS::Synthetics::Canary
          file_path: synthetic/synthetic.yaml
          prancer_unique_id: f4c85322-5a75-473e-ae6d-dc0e32620eae
      StartCanaryAfterCreation: false
