AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - '*'
                - arn:aws:iam::123456789012:user/Alice
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      EncryptionConfiguration:
        EncryptionType: KMS
        KmsKey: String<specify the AWS KMS key to use for encryption. The alias, key
          ID, or full ARN of the AWS KMS key can be specified>
