AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
