AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  lifecyclePolicyText:
    Type: String
  repositoryName:
    Type: String
  registryId:
    Type: String
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
Outputs:
  Arn:
    Value: !GetAtt 'MyRepository.Arn'
