AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InputStreamCFB159EA:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 16
      RetentionPeriodHours: 24
      Tags:
        - created_timestamp: 1646367738
          last_modified_timestamp: 1646367738
          resource_name: InputStreamCFB159EA
          resource_type: AWS::Kinesis::Stream
          file_path: kinesis/kinesis.yaml
          prancer_unique_id: 4235400a-cff7-4271-b2b2-d9f0f4941ab1
    Metadata:
      aws:cdk:path: StreamingEtl/InputStream/Resource
