AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties: {}
  CT:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      IsMultiRegionTrail: false
      EnableLogFileValidation: false
      IncludeGlobalServiceEvents: true
      S3BucketName: !Ref 'S3Bucket'
      EventSelectors:
        - DataResources:
            - Type: AWS::DynamoDB::Table
      CloudWatchLogsRoleArn: String<Specifies the role for the CloudWatch Logs endpoint
        to assume to write to a user's log group>
      CloudWatchLogsLogGroupArn: String<Specifies a log group name using an Amazon
        Resource Name (ARN), a unique identifier that represents the log group to
        which CloudTrail logs are delivered>
    DependsOn:
      - Topic
      - S3BucketPolicy
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: {}
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3Bucket'
      PolicyDocument:
        Id: CrossAccessPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEveryoneReadOnlyAccess
            Effect: Allow
            Principal: '*'
            Action:
              - s3:*
            Resource:
              - !GetAtt 'S3Bucket.Arn'
              - !Sub '${S3Bucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: true
