AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: Topic
          resource_type: AWS::SNS::Topic
          file_path: cloudtrail/cloudtrail.yaml
          prancer_unique_id: ee1720d4-f107-4f45-943f-9e281316d86d
  CT:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      IsMultiRegionTrail: false
      EnableLogFileValidation: false
      IncludeGlobalServiceEvents: true
      S3BucketName: !Ref 'S3Bucket'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: CT
          resource_type: AWS::CloudTrail::Trail
          file_path: cloudtrail/cloudtrail.yaml
          prancer_unique_id: '0e270bf1-8a81-49cf-9a57-c3deaf91af9c'
    DependsOn:
      - Topic
      - S3BucketPolicy
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: S3Bucket
          resource_type: AWS::S3::Bucket
          file_path: cloudtrail/cloudtrail.yaml
          prancer_unique_id: b69f762c-e7d9-4411-abc6-43fdb3d01350
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3Bucket'
      PolicyDocument:
        Id: CrossAccessPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEveryoneReadOnlyAccess
            Effect: Allow
            Principal: '*'
            Action:
              - s3:*
            Resource:
              - !GetAtt 'S3Bucket.Arn'
              - !Sub '${S3Bucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: true
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: S3BucketPolicy
          resource_type: AWS::S3::BucketPolicy
          file_path: cloudtrail/cloudtrail.yaml
          prancer_unique_id: 981431f9-3e49-4b69-9403-bb4a54b36123
