AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
    OperatorEmail: 
      Description: "Email address to notify when new logs are published."
      Type: String
  Resources: 
    S3Bucket: 
      DeletionPolicy: Retain
      Type: AWS::S3::Bucket
      Properties: {}
    SampleBucketPolicy:
  Type: 'AWS::S3::BucketPolicy'
  Properties:
    Bucket: !Ref DOC-EXAMPLE-BUCKET
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Action:
            - 's3:GetObject'
          Effect: Allow
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref DOC-EXAMPLE-BUCKET
              - /*
          Principal: '*'
          Condition:
            StringLike:
              'aws:Referer':
                - 'http://www.example.com/*'
                - 'http://example.net/*'
    Topic: 
      Type: AWS::SNS::Topic
      Properties: 
        Subscription: 
          - 
            Endpoint: 
              Ref: OperatorEmail
            Protocol: email
    TopicPolicy: 
      Type: AWS::SNS::TopicPolicy
      Properties: 
        Topics: 
          - Ref: "Topic"
        PolicyDocument: 
          Version: "2008-10-17"
          Statement: 
            - 
              Sid: "AWSCloudTrailSNSPolicy"
              Effect: "Allow"
              Principal: 
                Service: "cloudtrail.amazonaws.com"
              Resource: "*"
              Action: "SNS:Publish"
    myTrail: 
      DependsOn: 
        - BucketPolicy
        - TopicPolicy
      Type: AWS::CloudTrail::Trail
      Properties: 
        S3BucketName: 
          Ref: S3Bucket
        SnsTopicName: 
          Fn::GetAtt: 
            - Topic
            - TopicName
        IsLogging: true
        IsMultiRegionTrail: false
        EnableLogFileValidation: false