AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FileSystemResource:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      PerformanceMode: maxIO
      Encrypted: false
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      FileSystemTags:
        - Key: Name
          Value: TestFileSystem
      FileSystemPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: '*'
            Principal: '*'
      KmsKeyId: !GetAtt 'key.Arn'
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: FileSystemResource
          resource_type: AWS::EFS::FileSystem
          file_path: efs/efs.yaml
          prancer_unique_id: cedbf361-aa57-48d5-8c46-5fc0c05f6cff
  key:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - :root
            Action:
              - kms:*
            Resource:
              - '*'
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: key
          resource_type: AWS::KMS::Key
          file_path: efs/efs.yaml
          prancer_unique_id: 8474e7f8-6a1b-4623-a496-f03d6a1e9626
