AWSTemplateFormatVersion: '2010-09-09'
Description: "Example REST API with a Lambda authorizer. To invoke the API, clients\
  \ must include specific\nheader and query string values in the request.\n"
Resources:
  MyAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: example-rest-api-with-auth
      EndpointConfiguration:
        Types:
          - EDGE
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: MyAPI
          resource_type: AWS::ApiGateway::RestApi
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: 91e6951e-8484-4f23-937b-25e1b4fadfc6
  MyAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerCredentials: !GetAtt 'InvokeRole.Arn'
      AuthorizerUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyAuthFunction.Arn}/invocations'
      IdentitySource: method.request.header.HeaderAuth1,method.request.querystring.QueryString1
      Name: my-authorizer
      RestApiId: !Ref 'MyAPI'
      Type: COGNITO_USER_POOLS
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: MyAuthorizer
          resource_type: AWS::ApiGateway::Authorizer
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: 2d03b738-463d-4ee1-bc2c-ba126481cbfa
  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref 'PetsResource'
      RestApiId: !Ref 'MyAPI'
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        Uri: http://petstore.execute-api.us-west-1.amazonaws.com/petstore/pets
        IntegrationHttpMethod: GET
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: Method
          resource_type: AWS::ApiGateway::Method
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: 3a226f65-f7b4-40d7-bb92-0a69cd511852
  Deployment:
    DependsOn: Method
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref 'MyAPI'
      StageName: tempstage
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: Deployment
          resource_type: AWS::ApiGateway::Deployment
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: '0e861278-a06c-471e-8c18-c473e8f1b118'
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: invokeauth
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt 'MyAuthFunction.Arn'
        - PolicyName: invokelambdaproxy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt 'MyProxyFunction.Arn'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: InvokeRole
          resource_type: AWS::IAM::Role
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: '07086071-6b84-47c6-bcd1-0d7cd4a03498'
  MyAuthFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt 'FunctionExecutionRole.Arn'
      Handler: index.handler
      Code:
        ZipFile: "exports.handler = function(event, context, callback) {\n  console.log('Received\
          \ event:', JSON.stringify(event, null, 2));\n  // A simple request-based\
          \ authorizer example to demonstrate how to use request\n  // parameters\
          \ to allow or deny a request. In this example, a request is\n  // authorized\
          \ if the client-supplied HeaderAuth1 header and QueryString1\n  // query\
          \ parameter match 'headerValue1' and 'queryValue1'.\n  // Retrieve request\
          \ parameters from the Lambda function input:\n  var headers = event.headers;\n\
          \  var queryStringParameters = event.queryStringParameters;\n  var pathParameters\
          \ = event.pathParameters;\n  var stageVariables = event.stageVariables;\n\
          \      \n  // Parse the input for the parameter values\n  var tmp = event.methodArn.split(':');\n\
          \  var apiGatewayArnTmp = tmp[5].split('/');\n  var awsAccountId = tmp[4];\n\
          \  var region = tmp[3];\n  var restApiId = apiGatewayArnTmp[0];\n  var stage\
          \ = apiGatewayArnTmp[1];\n  var method = apiGatewayArnTmp[2];\n  var resource\
          \ = '/'; // root resource\n  if (apiGatewayArnTmp[3]) {\n      resource\
          \ += apiGatewayArnTmp[3];\n  }\n      \n  // Perform authorization to return\
          \ the Allow policy for correct parameters and \n  // the 'Unauthorized'\
          \ error, otherwise.\n  var authResponse = {};\n  var condition = {};\n \
          \ condition.IpAddress = {};\n  \n  if (headers.HeaderAuth1 === \"headerValue1\"\
          \n      && queryStringParameters.QueryString1 === \"queryValue1\") {\n \
          \     callback(null, generateAllow('me', event.methodArn));\n  }  else {\n\
          \      callback(\"Unauthorized\");\n  }\n  }\n  \n  // Helper function to\
          \ generate an IAM policy\n  var generatePolicy = function(principalId, effect,\
          \ resource) {\n  // Required output:\n  var authResponse = {};\n  authResponse.principalId\
          \ = principalId;\n  if (effect && resource) {\n      var policyDocument\
          \ = {};\n      policyDocument.Version = '2012-10-17'; // default version\n\
          \      policyDocument.Statement = [];\n      var statementOne = {};\n  \
          \    statementOne.Action = 'execute-api:Invoke'; // default action\n   \
          \   statementOne.Effect = effect;\n      statementOne.Resource = resource;\n\
          \      policyDocument.Statement[0] = statementOne;\n      authResponse.policyDocument\
          \ = policyDocument;\n  }\n  // Optional output with custom properties of\
          \ the String, Number or Boolean type.\n  authResponse.context = {\n    \
          \  \"stringKey\": \"stringval\",\n      \"numberKey\": 123,\n      \"booleanKey\"\
          : true\n  };\n  return authResponse;\n  }\n      \n  var generateAllow =\
          \ function(principalId, resource) {\n      return generatePolicy(principalId,\
          \ 'Allow', resource);\n  }\n      \n  var generateDeny = function(principalId,\
          \ resource) {\n      return generatePolicy(principalId, 'Deny', resource);\n\
          \  }\n"
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: MyAuthFunction
          resource_type: AWS::Lambda::Function
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: a88d3ee6-9002-444f-b1d4-b5836ffa04db
  MyProxyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt 'FunctionExecutionRole.Arn'
      Handler: index.handler
      Code:
        ZipFile: "exports.handler = async (event) => {\n    const response = {\n \
          \       statusCode: 200,\n        body: JSON.stringify('Hello from Lambda!'),\n\
          \    };\n    return response;\n};\n"
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: MyProxyFunction
          resource_type: AWS::Lambda::Function
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: b073a218-cc6e-4064-9798-e6e6a74d899d
  FunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: FunctionExecutionRole
          resource_type: AWS::IAM::Role
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: c9dd7759-91d8-47a1-8f79-5b77ca19a885
  PetsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt 'MyAPI.RootResourceId'
      PathPart: pets
      RestApiId: !Ref 'MyAPI'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: PetsResource
          resource_type: AWS::ApiGateway::Resource
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: 126c96cd-432a-43e4-b8f8-831a431a6f5d
  TestStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      ClientCertificateId: ''
      StageName: test
      RestApiId: !Ref 'MyAPI'
      DeploymentId: !Ref 'Deployment'
      Description: test stage description
      AccessLogSetting:
        DestinationArn: !GetAtt 'MyLogGroup.Arn'
        Format: >-
          $context.identity.sourceIp $context.identity.caller $context.identity.user
          [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol"
          $context.status $context.responseLength $context.requestId
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: TestStage
          resource_type: AWS::ApiGateway::Stage
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: e06b5e4e-b910-4425-b881-f7d4b64cb038
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - '-'
        - - !Ref 'MyAPI'
          - access-logs
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: MyLogGroup
          resource_type: AWS::Logs::LogGroup
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: 53715b20-9723-4f4d-a90b-f3bc4c37261f
  RequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: RequestValidatorAPI
      RestApiId: !Ref 'MyAPI'
      ValidateRequestBody: !false ''
      ValidateRequestParameters: false
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: RequestValidator
          resource_type: AWS::ApiGateway::RequestValidator
          file_path: api_gateway/api_gateway.yaml
          prancer_unique_id: 1a59c0b7-d323-4d47-a3dd-1810f04daee6
Outputs:
  InvokeURL:
    Value: !Sub 'https://${MyAPI}.execute-api.${AWS::Region}.amazonaws.com/test'
