AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://test-prancer.s3.amazonaws.com/cf_test.yaml
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: myStackWithParams
          resource_type: AWS::CloudFormation::Stack
          file_path: cloudformation/cloudformation.yaml
          prancer_unique_id: 22588385-12c6-4eee-9cc3-b23dda67e08f
