AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://test-prancer.s3.amazonaws.com/cf_test.yaml
      NotificationARNs: String<The Simple Notification Service (SNS) topic ARNs to
        publish stack related events>
