AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: mybucket.s3.amazonaws.com
            Id: myS3Origin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1
                - TLSv1.1
                - TLSv1.2
                - SSLv3
        Enabled: 'true'
        Comment: Some comment
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
        ViewerCertificate:
          MinimumProtocolVersion: SSLv3
          CloudFrontDefaultCertificate: 'true'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646302584
          resource_name: myDistribution
          resource_type: AWS::CloudFront::Distribution
          file_path: cloudfront/cloudfront.yaml
          prancer_unique_id: f364d5a7-26ee-4efc-8fbb-26a5b9ddcb08
