AWSTemplateFormatVersion: '2010-09-09'
Description: Create a basic Amazon MQ for RabbitMQ broker
Resources:
  BasicBroker:
    Type: AWS::AmazonMQ::Broker
    Properties:
      AutoMinorVersionUpgrade: 'false'
      BrokerName: MyBasicRabbitBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: RabbitMQ
      EngineVersion: 3.8.6
      HostInstanceType: mq.t3.micro
      PubliclyAccessible: 'true'
      Users:
        - Password: AmazonMqPassword
          Username: AmazonMqUsername
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: BasicBroker
          resource_type: AWS::AmazonMQ::Broker
          file_path: /tmp/tmpxofsolel/mq/mq.yaml
          prancer_unique_id: 8a49abee-7b43-46e6-a972-8e316d0280df
