AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SampleSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - https://sqs:us-east-2.amazonaws.com/444455556666/queue2
      PolicyDocument:
        Statement:
          - Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
              - '*'
            Effect: Allow
            Resource: arn:aws:sqs:us-east-2:444455556666:queue2
            Principal:
              AWS:
                - '111122223333'
                - '*'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1651757277
        - Key: resource_name
          Value: SampleSQSPolicy
        - Key: resource_type
          Value: AWS::SQS::QueuePolicy
        - Key: prancer_unique_id
          Value: 3c41ecca-303c-4ce8-88eb-2ab6db3eea29
