AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SampleSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - https://sqs:us-east-2.amazonaws.com/444455556666/queue2
      PolicyDocument:
        Statement:
          - Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
              - '*'
            Effect: Allow
            Resource: arn:aws:sqs:us-east-2:444455556666:queue2
            Principal:
              AWS:
                - '111122223333'
                - '*'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: SampleSQSPolicy
          resource_type: AWS::SQS::QueuePolicy
          file_path: sqs/sqs.yaml
          prancer_unique_id: dc073482-3b05-4a07-a9be-c5850ed96659
