AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaInvocationsAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: Invocations
      Namespace: AWS/Lambda
      Stat: Sum
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: LambdaInvocationsAnomalyDetector
          resource_type: AWS::CloudWatch::AnomalyDetector
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: 559d63d4-d73f-456d-b08d-bdf6970a5bed
  LambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
        - Expression: ANOMALY_DETECTION_BAND(m1, 2)
          Id: ad1
          AccountId: 1234567890
        - Id: m1
          MetricStat:
            Metric:
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: breaching
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: LambdaInvocationsAlarm
          resource_type: AWS::CloudWatch::Alarm
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: 57bd53ca-2c2c-4908-82ff-58f64aac6507
