AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaInvocationsAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: Invocations
      Namespace: AWS/Lambda
      Stat: Sum
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: LambdaInvocationsAnomalyDetector
          resource_type: AWS::CloudWatch::AnomalyDetector
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: '011c324c-de25-4572-9e0f-a983e55c5ff9'
  LambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
        - Expression: ANOMALY_DETECTION_BAND(m1, 2)
          Id: ad1
          AccountId: 1234567890
        - Id: m1
          MetricStat:
            Metric:
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: breaching
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: LambdaInvocationsAlarm
          resource_type: AWS::CloudWatch::Alarm
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: 165d90f7-cd11-4085-a8be-5a5400246928
