AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaInvocationsAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: Invocations
      Namespace: AWS/Lambda
      Stat: Sum
      Tags:
        - created_timestamp: 1646300948
          last_modified_timestamp: 1646300948
          resource_name: LambdaInvocationsAnomalyDetector
          resource_type: AWS::CloudWatch::AnomalyDetector
          file_path: /tmp/tmpxofsolel/cloudwatch/cloudwatch.yaml
          prancer_unique_id: 7b52baba-8687-4155-a6ee-94a2b8b14cbb
  LambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
        - Expression: ANOMALY_DETECTION_BAND(m1, 2)
          Id: ad1
          AccountId: 1234567890
        - Id: m1
          MetricStat:
            Metric:
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: breaching
      Tags:
        - created_timestamp: 1646300948
          last_modified_timestamp: 1646300948
          resource_name: LambdaInvocationsAlarm
          resource_type: AWS::CloudWatch::Alarm
          file_path: /tmp/tmpxofsolel/cloudwatch/cloudwatch.yaml
          prancer_unique_id: b0dd6da2-aded-421c-afc7-aed575d6de48
