AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaInvocationsAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: Invocations
      Namespace: AWS/Lambda
      Stat: Sum
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646302585
          resource_name: LambdaInvocationsAnomalyDetector
          resource_type: AWS::CloudWatch::AnomalyDetector
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: 514c0a0e-408f-4d9a-a5ed-7994f226f371
  LambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
        - Expression: ANOMALY_DETECTION_BAND(m1, 2)
          Id: ad1
          AccountId: 1234567890
        - Id: m1
          MetricStat:
            Metric:
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: breaching
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646302585
          resource_name: LambdaInvocationsAlarm
          resource_type: AWS::CloudWatch::Alarm
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: 279887cb-ca3c-4057-9212-d952e256d880
