AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaInvocationsAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: Invocations
      Namespace: AWS/Lambda
      Stat: Sum
      Tags:
        - created_timestamp: 1646367738
          last_modified_timestamp: 1646367738
          resource_name: LambdaInvocationsAnomalyDetector
          resource_type: AWS::CloudWatch::AnomalyDetector
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: '0fc5190b-7054-4ec0-8ff4-788cd03b4d87'
  LambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
        - Expression: ANOMALY_DETECTION_BAND(m1, 2)
          Id: ad1
          AccountId: 1234567890
        - Id: m1
          MetricStat:
            Metric:
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 86400
            Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: breaching
      Tags:
        - created_timestamp: 1646367738
          last_modified_timestamp: 1646367738
          resource_name: LambdaInvocationsAlarm
          resource_type: AWS::CloudWatch::Alarm
          file_path: cloudwatch/cloudwatch.yaml
          prancer_unique_id: 6654d1f8-d204-42de-ade4-74c4ba238d03
