AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed
      to
    Type: List<AWS::EC2::Subnet::Id>
    Default: !Ref 'Subnets'
  SecurityGroups:
    Description: Choose which security group you want to apply
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: !Ref 'SecurityGroups'
  RoleArn:
    Type: String
    Default: arn:aws:iam::155603667260:role/eks-cluster
Resources:
  myCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: 1.9.1
      Name: prod
      RoleArn: !Ref 'RoleArn'
      EndpointPrivateAccess: false
      EndpointPublicAccess: true
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref 'SecurityGroups'
        SubnetIds: !Ref 'Subnets'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1651757277
        - Key: resource_name
          Value: myCluster
        - Key: resource_type
          Value: AWS::EKS::Cluster
        - Key: prancer_unique_id
          Value: 59ed95c8-eff5-4877-879f-fc546c8fe02f
