AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Example:
    Type: AWS::Glue::DataCatalogEncryptionSettings
    Properties:
      DataCatalogEncryptionSettings:
        ConnectionPasswordEncryption:
          KmsKeyId: ''
          ReturnConnectionPasswordEncrypted: false
        EncryptionAtRest:
          SseAwsKmsKeyId: ''
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: Example
          resource_type: AWS::Glue::DataCatalogEncryptionSettings
          file_path: glue/glue.yaml
          prancer_unique_id: 4122cbce-89a2-4f51-a7f1-6de43fe62025
  Example2:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      Name: GlueEncryptionConfiguration
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: Example2
          resource_type: AWS::Glue::SecurityConfiguration
          file_path: glue/glue.yaml
          prancer_unique_id: c5e03f7d-46fb-4757-ad4d-e8f256d5dcba
