AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Example:
    Type: AWS::Glue::DataCatalogEncryptionSettings
    Properties:
      DataCatalogEncryptionSettings:
        ConnectionPasswordEncryption:
          KmsKeyId: ''
          ReturnConnectionPasswordEncrypted: false
        EncryptionAtRest:
          SseAwsKmsKeyId: ''
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: Example
          resource_type: AWS::Glue::DataCatalogEncryptionSettings
          file_path: glue/glue.yaml
          prancer_unique_id: 9a6c8bcb-5f34-4cd9-94b0-d0376ced6c7f
  Example2:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      Name: GlueEncryptionConfiguration
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: Example2
          resource_type: AWS::Glue::SecurityConfiguration
          file_path: glue/glue.yaml
          prancer_unique_id: 2b5516bc-7b8b-4e7b-b977-b391c6eb9197
