AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Example:
    Type: AWS::Glue::DataCatalogEncryptionSettings
    Properties:
      DataCatalogEncryptionSettings:
        ConnectionPasswordEncryption:
          KmsKeyId: ''
          ReturnConnectionPasswordEncrypted: false
        EncryptionAtRest:
          SseAwsKmsKeyId: ''
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646302585
          resource_name: Example
          resource_type: AWS::Glue::DataCatalogEncryptionSettings
          file_path: glue/glue.yaml
          prancer_unique_id: fd69c124-1652-4cc2-8887-61eb56c967f5
  Example2:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      Name: GlueEncryptionConfiguration
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646302585
          resource_name: Example2
          resource_type: AWS::Glue::SecurityConfiguration
          file_path: glue/glue.yaml
          prancer_unique_id: 12ed9416-645a-4f9b-8e08-db32044a998d
