AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Example:
    Type: AWS::Glue::DataCatalogEncryptionSettings
    Properties:
      DataCatalogEncryptionSettings:
        ConnectionPasswordEncryption:
          KmsKeyId: ''
          ReturnConnectionPasswordEncrypted: false
        EncryptionAtRest:
          SseAwsKmsKeyId: ''
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: Example
          resource_type: AWS::Glue::DataCatalogEncryptionSettings
          file_path: /tmp/tmpxofsolel/glue/glue.yaml
          prancer_unique_id: ef5f0c00-5c79-4267-9df4-73fdc487e981
  Example2:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      Name: GlueEncryptionConfiguration
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: Example2
          resource_type: AWS::Glue::SecurityConfiguration
          file_path: /tmp/tmpxofsolel/glue/glue.yaml
          prancer_unique_id: '021026e7-9ffe-4cd1-956a-fadadae77106'
