AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ServiceName:
    Type: String
    Default: nginx
    Description: A name for the service
  ImageUrl:
    Type: String
    Default: nginx
    Description: The url of a docker image that contains the application process that
      will handle the traffic for this service
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port number the application inside the docker container is binding
      to
  ContainerCpu:
    Type: Number
    Default: 0
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 0
    Description: How much memory in megabytes to give the container
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'ServiceName'
      Cpu: !Ref 'ContainerCpu'
      Memory: !Ref 'ContainerMemory'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref 'ServiceName'
          User: root
          Cpu: !Ref 'ContainerCpu'
          Memory: !Ref 'ContainerMemory'
          Image: !Ref 'ImageUrl'
          Privileged: true
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'
      ExecutionRoleArn: String<The Amazon Resource Name (ARN) of the task execution
        role that grants the Amazon ECS container agent permission to make AWS API
        calls on your behalf>
      TaskRoleArn: String<The short name or full Amazon Resource Name (ARN) of the
        AWS Identity and Access Management role that grants containers in the task
        permission to call AWS APIs on your behalf>
