AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora serverless cluster
Parameters:
  DatabaseName:
    Type: String
    Default: mydatabase
  EngineVersion:
    Type: String
    Default: '5.6'
  MasterUsername:
    Type: String
    Default: root
  MasterUserPassword:
    Type: String
    NoEcho: true
    Default: masterpassword
  VpcSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Default: dbuser
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Default: dbpassword
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: !Ref 'EngineVersion'
      DatabaseName: !Ref 'DatabaseName'
      MasterUsername: !Ref 'MasterUsername'
      MasterUserPassword: Root1234
      BackupRetentionPeriod: 0
      DeletionProtection: false
      StorageEncrypted: false
      VpcSecurityGroupIds:
        - !Ref 'VpcSecurityGroupId'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: Cluster
          resource_type: AWS::RDS::DBCluster
          file_path: rds/rds.yaml
          prancer_unique_id: 19a32b5c-f077-4602-a81b-883b1f10f241
  myDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100'
      DBInstanceClass: db.t2.small
      Engine: MySQL
      Iops: '1000'
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      StorageEncrypted: false
      MultiAZ: false
      CopyTagsToSnapshot: false
      BackupRetentionPeriod: 0
      AutoMinorVersionUpgrade: false
      PubliclyAccessible: true
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: myDB
          resource_type: AWS::RDS::DBInstance
          file_path: rds/rds.yaml
          prancer_unique_id: d27a6498-a842-4d4d-bfb9-6b1277ca161b
  GlobalCluster:
    Type: AWS::RDS::GlobalCluster
    Properties:
      GlobalClusterIdentifier: ''
      SourceDBClusterIdentifier: !Ref 'Cluster'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: GlobalCluster
          resource_type: AWS::RDS::GlobalCluster
          file_path: rds/rds.yaml
          prancer_unique_id: 93fa5420-ec1a-42e4-8b24-3c780bd5f931
