AWSTemplateFormatVersion: '2010-09-09'
Description: Basic NotebookInstance test update to a different instance type
Resources:
  BasicNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t2.large
      RoleArn: !GetAtt 'ExecutionRole.Arn'
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: BasicNotebookInstance
          resource_type: AWS::SageMaker::NotebookInstance
          file_path: /tmp/tmpxofsolel/sagemaker/sagemaker.yaml
          prancer_unique_id: '0bca866f-96f4-42b1-bac2-6c92685da374'
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: ExecutionRole
          resource_type: AWS::IAM::Role
          file_path: /tmp/tmpxofsolel/sagemaker/sagemaker.yaml
          prancer_unique_id: a8c3abc3-6138-4e17-a5e1-d608031ef73f
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref 'BasicNotebookInstance'
