AWSTemplateFormatVersion: '2010-09-09'
Description: Basic NotebookInstance test update to a different instance type
Resources:
  BasicNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t2.large
      RoleArn: !GetAtt 'ExecutionRole.Arn'
      subnetId: String<The ID of the subnet in a VPC to which you would like to have
        a connectivity from your ML compute instance>
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref 'BasicNotebookInstance'
