AWSTemplateFormatVersion: '2010-09-09'
Description: Basic NotebookInstance test update to a different instance type
Resources:
  BasicNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t2.large
      RoleArn: !GetAtt 'ExecutionRole.Arn'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301465
          resource_name: BasicNotebookInstance
          resource_type: AWS::SageMaker::NotebookInstance
          file_path: sagemaker/sagemaker.yaml
          prancer_unique_id: 40fd5539-300b-452a-9148-581d4b442f5e
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301465
          resource_name: ExecutionRole
          resource_type: AWS::IAM::Role
          file_path: sagemaker/sagemaker.yaml
          prancer_unique_id: 6c1aa7b4-a378-4afb-b106-423535817697
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref 'BasicNotebookInstance'
