AWSTemplateFormatVersion: '2010-09-09'
Description: Basic NotebookInstance test update to a different instance type
Resources:
  BasicNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t2.large
      RoleArn: !GetAtt 'ExecutionRole.Arn'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: BasicNotebookInstance
          resource_type: AWS::SageMaker::NotebookInstance
          file_path: sagemaker/sagemaker.yaml
          prancer_unique_id: 72955ff2-9e5c-470f-a41d-d42f5a87a4b0
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: ExecutionRole
          resource_type: AWS::IAM::Role
          file_path: sagemaker/sagemaker.yaml
          prancer_unique_id: e1655f3e-db5d-4819-ac4e-d7ef7bf684d0
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref 'BasicNotebookInstance'
