AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  myLaunchTemplateVersionNumber:
    Type: String
    Default: !Ref 'myLaunchTemplateVersionNumber'
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: !Ref 'Subnets'
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        CreditSpecification:
          CpuCredits: Unlimited
        ImageId: !Ref 'LatestAmiId'
        InstanceType: t2.micro
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: myLaunchTemplate
          resource_type: AWS::EC2::LaunchTemplate
          file_path: auto_scale/autoscale.yaml
          prancer_unique_id: 529b6620-d0d2-4e00-8043-ea31f9e8b288
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '0'
      MaxSize: '1'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref 'myLaunchTemplate'
        Version: !Ref 'myLaunchTemplateVersionNumber'
      VPCZoneIdentifier: !Ref 'Subnets'
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      LoadBalancerNames:
        - !Ref 'ElasticLoadBalancer'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: myASG
          resource_type: AWS::AutoScaling::AutoScalingGroup
          file_path: auto_scale/autoscale.yaml
          prancer_unique_id: a766f08c-1a41-4d7f-85dd-9ddc4c49fa1a
  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: !GetAZs ''
      CrossZone: 'true'
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: ElasticLoadBalancer
          resource_type: AWS::ElasticLoadBalancing::LoadBalancer
          file_path: auto_scale/autoscale.yaml
          prancer_unique_id: ddb4d315-becc-4013-9e45-52b44c2283b6
