AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  myLaunchTemplateVersionNumber:
    Type: String
    Default: !Ref 'myLaunchTemplateVersionNumber'
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: !Ref 'Subnets'
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        CreditSpecification:
          CpuCredits: Unlimited
        ImageId: !Ref 'LatestAmiId'
        InstanceType: t2.micro
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: myLaunchTemplate
          resource_type: AWS::EC2::LaunchTemplate
          file_path: auto_scale/autoscale.yaml
          prancer_unique_id: 412567bc-7a70-4ed4-908b-b53c07fb8ff5
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '0'
      MaxSize: '1'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref 'myLaunchTemplate'
        Version: !Ref 'myLaunchTemplateVersionNumber'
      VPCZoneIdentifier: !Ref 'Subnets'
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      LoadBalancerNames:
        - !Ref 'ElasticLoadBalancer'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: myASG
          resource_type: AWS::AutoScaling::AutoScalingGroup
          file_path: auto_scale/autoscale.yaml
          prancer_unique_id: 691c7d9f-dd1d-4e7f-9fdd-06578d8b6f69
  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: !GetAZs ''
      CrossZone: 'true'
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: ElasticLoadBalancer
          resource_type: AWS::ElasticLoadBalancing::LoadBalancer
          file_path: auto_scale/autoscale.yaml
          prancer_unique_id: dc7aa6a8-e264-473e-b881-5b60935dcb73
