AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS ElatiCache for Redis - Cluster Mode Demonstration
Parameters:
  ProjectName:
    Type: String
    Default: aws-elasticache-cluster-mode
  ElasticacheInstanceClass:
    Type: String
    Default: cache.r5.large
Globals:
  Function:
    Runtime: ruby2.5
    Handler: app.handler
    MemorySize: 1024
    Timeout: 15
    Tracing: Active
    Tags:
      Project: !Ref 'ProjectName'
Mappings:
  SubnetConfig:
    VPC:
      CIDR: 10.0.0.0/16
    Private1:
      CIDR: 10.0.0.0/24
    Private2:
      CIDR: 10.0.1.0/24
    Lambda1:
      CIDR: 10.0.2.0/24
    Lambda2:
      CIDR: 10.0.3.0/24
    Public1:
      CIDR: 10.0.4.0/24
Resources:
  RedisCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AutoMinorVersionUpgrade: true
      CacheParameterGroupName: default.redis5.0.cluster.on
      CacheNodeType: !Ref 'ElasticacheInstanceClass'
      CacheSubnetGroupName: !Ref 'RedisSubnetGroup'
      Engine: redis
      EngineVersion: 5.0.4
      NumNodeGroups: 1
      Port: 6379
      ReplicasPerNodeGroup: 1
      ReplicationGroupDescription: Sample Redis group for scaling
      SecurityGroupIds:
        - !Ref 'RedisSecurityGroup'
      Tags:
        - Key: Project
          Value: !Ref 'ProjectName'
      AutomaticFailoverEnabled: true
      TransitEncryptionEnabled: false
      AtRestEncryptionEnabled: false
