AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS ElatiCache for Redis - Cluster Mode Demonstration
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  Subnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
    Default: !Ref 'Subnets'
  InstanceType:
    Description: Which instance type should we use to build the ECS cluster?
    Type: String
    Default: cache.t3.medium
  SecurityGroups:
    Description: Select the Security Group to use for the ECS cluster hosts
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub '${EnvironmentName}-Subnet-${AWS::Region}'
      Description: The subnet group for the reactive application architecture
      SubnetIds: !Ref 'Subnets'
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646302584
          resource_name: CacheSubnetGroup
          resource_type: AWS::ElastiCache::SubnetGroup
          file_path: elasticache/elasticache.yaml
          prancer_unique_id: 597eccdc-be79-482c-9d8f-82fc3c9e3a28
  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      KmsKeyId: ''
      CacheNodeType: !Ref 'InstanceType'
      CacheSubnetGroupName: !Ref 'CacheSubnetGroup'
      Engine: redis
      EngineVersion: 6.x
      NumCacheClusters: 2
      Port: 6379
      ReplicationGroupDescription: !Sub '${EnvironmentName}-ReplicationGroup-${AWS::Region}'
      SecurityGroupIds:
        - !Ref 'SecurityGroups'
      AutomaticFailoverEnabled: false
      TransitEncryptionEnabled: false
      AtRestEncryptionEnabled: false
      AutoMinorVersionUpgrade: true
      CacheSecurityGroupNames: []
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646302584
          resource_name: ReplicationGroup
          resource_type: AWS::ElastiCache::ReplicationGroup
          file_path: elasticache/elasticache.yaml
          prancer_unique_id: '0c33e177-618e-40e6-ae48-ce736d1df926'
