AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: >-
  AWS CloudFormation Sample Template Config: This template demonstrates the usage
  of AWS Config resources. **WARNING** You will be billed for the AWS resources used
  if you create a stack from this template.
Resources:
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: MyConfigRecorder
      RecordingGroup:
        ResourceTypes: []
      RoleARN: !GetAtt 'ConfigRole.Arn'
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: ConfigRecorder
          resource_type: AWS::Config::ConfigurationRecorder
          file_path: /tmp/tmpxofsolel/config/config.yaml
          prancer_unique_id: 3776883b-994e-4800-9c98-cb6b51ed0e0d
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: ConfigBucket
          resource_type: AWS::S3::Bucket
          file_path: /tmp/tmpxofsolel/config/config.yaml
          prancer_unique_id: 5ddb5c84-a6d6-40b4-9db5-9e9f88d6aa63
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetBucketAcl
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref 'ConfigBucket'
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref 'ConfigBucket'
                    - /AWSLogs/
                    - !Ref 'AWS::AccountId'
                    - /*
                Condition:
                  StringEquals:
                    s3:x-amz-acl: bucket-owner-full-control
              - Effect: Allow
                Action: config:Put*
                Resource: '*'
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: ConfigRole
          resource_type: AWS::IAM::Role
          file_path: /tmp/tmpxofsolel/config/config.yaml
          prancer_unique_id: d8904c9a-2e38-4342-882a-a54fe1009562
