AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  WithSpotPrice: !Not
    - !Equals
      - !Ref 'SpotPrice'
      - '0'
Description: Sample CloudFormation template for creating an EMR cluster
Parameters:
  GcTimeRatioValue:
    Default: '19'
    Description: Hadoop name node garbage collector time ratio
    Type: Number
  SpotPrice:
    Default: '0.1'
    Description: Spot price (or use 0 for 'on demand' instance)
    Type: Number
  Subnet:
    Description: Subnet ID for creating the EMR cluster
    Type: AWS::EC2::Subnet::Id
    Default: !Ref 'Subnet'
Resources:
  EMRInstanceProfile:
    Properties:
      Roles:
        - !Ref 'EMRJobFlowRole'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: EMRInstanceProfile
          resource_type: AWS::IAM::InstanceProfile
          file_path: emr/emr.yaml
          prancer_unique_id: 88c05e2b-b5cc-4371-a2ec-314a953f432c
    Type: AWS::IAM::InstanceProfile
    Metadata:
      AWS::CloudFormation::Designer:
        id: 4ce96dbe-d564-4f30-a44e-a0e7f6e46690
  EMRJobFlowRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: EMRJobFlowRole
          resource_type: AWS::IAM::Role
          file_path: emr/emr.yaml
          prancer_unique_id: 224e2590-bad8-4be9-a0ce-b9a9918a289a
    Type: AWS::IAM::Role
    Metadata:
      AWS::CloudFormation::Designer:
        id: 7935bef0-f0ed-4ee1-826b-75b2baadba34
  EMRSampleCluster:
    Properties:
      Applications:
        - Name: Hadoop
        - Name: Hive
        - Name: Pig
        - Name: Spark
      BootstrapActions:
        - Name: Dummy bootstrap action
          ScriptBootstrapAction:
            Args:
              - dummy
              - parameter
            Path: file:/usr/share/aws/emr/scripts/install-hue
      Configurations:
        - Classification: core-site
          ConfigurationProperties:
            hadoop.security.groups.cache.secs: '250'
        - Classification: mapred-site
          ConfigurationProperties:
            mapred.tasktracker.map.tasks.maximum: '2'
            mapreduce.map.sort.spill.percent: '90'
            mapreduce.tasktracker.reduce.tasks.maximum: '5'
        - Classification: hadoop-env
          Configurations:
            - Classification: export
              ConfigurationProperties:
                HADOOP_DATANODE_HEAPSIZE: '2048'
                HADOOP_NAMENODE_OPTS: -XX:GCTimeRatio=19
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m4.large
          Market: ON_DEMAND
          Name: cfnMaster
        CoreInstanceGroup:
          AutoScalingPolicy:
            Constraints:
              MaxCapacity: '3'
              MinCapacity: '1'
            Rules:
              - Action:
                  Market: ON_DEMAND
                  SimpleScalingPolicyConfiguration:
                    AdjustmentType: EXACT_CAPACITY
                    CoolDown: '300'
                    ScalingAdjustment: '1'
                Description: CoreAutoScalingPolicy rules
                Name: CoreAutoScalingPolicy
                Trigger:
                  CloudWatchAlarmDefinition:
                    ComparisonOperator: GREATER_THAN
                    Dimensions:
                      - Key: my.custom.master.property
                        Value: my.custom.master.value
                    EvaluationPeriods: '120'
                    MetricName: TestMetric
                    Namespace: AWS/ElasticMapReduce
                    Period: '300'
                    Statistic: AVERAGE
                    Threshold: '50'
                    Unit: PERCENT
          BidPrice:
            Fn::If:
              - WithSpotPrice
              - !Ref 'SpotPrice'
              - !Ref 'AWS::NoValue'
            Ref: SpotPrice
          EbsConfiguration:
            EbsBlockDeviceConfigs:
              - VolumeSpecification:
                  SizeInGB: '10'
                  VolumeType: gp2
                VolumesPerInstance: '1'
            EbsOptimized: true
          InstanceCount: '1'
          InstanceType: m4.large
          Market: SPOT
          Name: Core Instance
        Ec2SubnetId: !Ref 'Subnet'
      JobFlowRole: !Ref 'EMRInstanceProfile'
      Name: EMR Sample Cluster
      ReleaseLabel: emr-6.3.0
      SecurityConfiguration: !Ref 'EMRSecurityConfiguration'
      ServiceRole: !Ref 'EMRServiceRole'
      Tags:
        - Key: Name
          Value: EMR Sample Cluster
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: EMRSampleCluster
          resource_type: AWS::EMR::Cluster
          file_path: emr/emr.yaml
          prancer_unique_id: b69192a1-59da-409e-9d3b-3b57ce74dd08
      VisibleToAllUsers: true
      AutoScalingRole: EMR_AutoScaling_DefaultRole
    Type: AWS::EMR::Cluster
    Metadata:
      AWS::CloudFormation::Designer:
        id: e94a5475-45f5-44f6-80e8-0d3fb38f6bfd
  EMRSecurityConfiguration:
    Properties:
      Name: EMRSampleClusterSecurityConfiguration
      SecurityConfiguration:
        EncryptionConfiguration:
          AtRestEncryptionConfiguration:
            LocalDiskEncryptionConfiguration:
              AwsKmsKey: arn:aws:kms:us-east-1:123456789012:key/1234-1234-1234-1234-1234
              EncryptionKeyProviderType: AwsKms
            S3EncryptionConfiguration:
              AwsKmsKey: arn:aws:kms:us-east-1:123456789012:key/1234-1234-1234-1234-1234
              EncryptionMode: SSE-KMS
          EnableAtRestEncryption: false
          EnableInTransitEncryption: false
          InTransitEncryptionConfiguration:
            TLSCertificateConfiguration:
              CertificateProviderType: PEM
              S3Object: s3://MyConfigStore/artifacts/MyCerts.zip
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: EMRSecurityConfiguration
          resource_type: AWS::EMR::SecurityConfiguration
          file_path: emr/emr.yaml
          prancer_unique_id: 253ee8c1-225e-4fd7-a7fa-93dd67ec059a
    Type: AWS::EMR::SecurityConfiguration
    Metadata:
      AWS::CloudFormation::Designer:
        id: 400d803c-fd1e-4a9e-92e9-4bb90f23831b
  EMRServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - elasticmapreduce.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: EMRServiceRole
          resource_type: AWS::IAM::Role
          file_path: emr/emr.yaml
          prancer_unique_id: 33c73f66-aeb3-4eab-8d65-086f70967db9
    Type: AWS::IAM::Role
    Metadata:
      AWS::CloudFormation::Designer:
        id: 487939b2-57e4-4bfd-bb48-b361400d29ae
  TestStep:
    Properties:
      ActionOnFailure: CONTINUE
      HadoopJarStep:
        Args:
          - '5'
          - '10'
        Jar: s3://emr-cfn-test/hadoop-mapreduce-examples-2.6.0.jar
        MainClass: pi
        StepProperties:
          - Key: my.custom.property
            Value: my.custom.value
      Name: TestStep
      VpcId: !Ref 'EMRSampleCluster'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: TestStep
          resource_type: AWS::EMR::Step
          file_path: emr/emr.yaml
          prancer_unique_id: 18aa73b0-97e0-4341-9a60-ff07f0d4a4b7
    Type: AWS::EMR::Step
    Metadata:
      AWS::CloudFormation::Designer:
        id: 3cea84fe-dd19-4f81-a096-11f383b7a893
Metadata:
  AWS::CloudFormation::Designer:
    487939b2-57e4-4bfd-bb48-b361400d29ae:
      size:
        width: 60
        height: 60
      position:
        x: 190
        y: 120
      z: 1
      embeds: []
    400d803c-fd1e-4a9e-92e9-4bb90f23831b:
      size:
        width: 60
        height: 60
      position:
        x: 430
        y: 120
      z: 1
      embeds: []
    7935bef0-f0ed-4ee1-826b-75b2baadba34:
      size:
        width: 60
        height: 60
      position:
        x: 60
        y: 230
      z: 1
      embeds: []
    4ce96dbe-d564-4f30-a44e-a0e7f6e46690:
      size:
        width: 60
        height: 60
      position:
        x: 320
        y: 230
      z: 1
      embeds: []
      isassociatedwith:
        - 7935bef0-f0ed-4ee1-826b-75b2baadba34
    e94a5475-45f5-44f6-80e8-0d3fb38f6bfd:
      size:
        width: 60
        height: 60
      position:
        x: 320
        y: 120
      z: 1
      embeds: []
    3cea84fe-dd19-4f81-a096-11f383b7a893:
      size:
        width: 60
        height: 60
      position:
        x: 320
        y: 0
      z: 0
      embeds: []
      iscontainedinside:
        - e94a5475-45f5-44f6-80e8-0d3fb38f6bfd
