AWSTemplateFormatVersion: '2010-09-09'
Description: github-codepipeline
Parameters:
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    AllowedPattern: '[a-z0-9A-Z_]*'
    Default: !Ref 'GitHubOAuthToken'
  GitHubOwner:
    Type: String
    Default: symphoniacloud
    AllowedPattern: '[A-Za-z0-9-]+'
  GitHubRepo:
    Type: String
    Default: github-codepipeline
    AllowedPattern: '[A-Za-z0-9-]+'
  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: '[A-Za-z0-9-]+'
  ApplicationStackName:
    Type: String
    Default: github-codepipeline-app
    AllowedPattern: '[A-Za-z0-9-]+'
Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: PipelineArtifactsBucket
          resource_type: AWS::S3::Bucket
          file_path: codepipeline/codepipeline.yaml
          prancer_unique_id: 4c926c59-5f14-48f5-961b-7a6872bcf58f
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref 'PipelineArtifactsBucket'
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt 'CodePipelineRole.Arn'
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: symphoniacloud
                Repo: github-codepipeline
                Branch: master
                PollForSourceChanges: false
                OAuthToken: !Ref 'GitHubOAuthToken'
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CloudFormationDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: SourceCode
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                RoleArn: !GetAtt 'CloudformationRole.Arn'
                StackName: github-codepipeline-app
                TemplatePath: !Sub 'SourceCode::application.yaml'
              RunOrder: 1
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: CodePipeline
          resource_type: AWS::CodePipeline::Pipeline
          file_path: codepipeline/codepipeline.yaml
          prancer_unique_id: b11a67de-65b3-4090-98ce-cfecaca63b24
  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref 'GitHubOAuthToken'
      RegisterWithThirdParty: 'true'
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref 'CodePipeline'
      TargetAction: Source
      TargetPipelineVersion: !GetAtt 'CodePipeline.Version'
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: GithubWebhook
          resource_type: AWS::CodePipeline::Webhook
          file_path: codepipeline/codepipeline.yaml
          prancer_unique_id: 9a3e13bd-6011-4186-b0b6-ddbe5041f1ea
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: CodePipelineRole
          resource_type: AWS::IAM::Role
          file_path: codepipeline/codepipeline.yaml
          prancer_unique_id: 77cb19f3-f5ec-4c7f-8f2b-ad624011c593
  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: CloudformationRole
          resource_type: AWS::IAM::Role
          file_path: codepipeline/codepipeline.yaml
          prancer_unique_id: a80fa165-dde3-46e2-9428-b6e513c09e94
