AWSTemplateFormatVersion: 2010-09-09
Description: MSK Cluster with all properties
Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
Resources:
  TestCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      ClusterName: ClusterWithAllProperties
      KafkaVersion: 2.2.1
      NumberOfBrokerNodes: 2
      EnhancedMonitoring: PER_BROKER
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: ""
        EncryptionInTransit:
          ClientBroker: PLAINTEXT
          InCluster: false
      Tags:
        Environment: Test
        Owner: QATeam
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        InstanceType: kafka.m5.large
        SecurityGroups: !Ref SecurityGroups
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 100
        ClientSubnets: !Ref SubnetIds