AWSTemplateFormatVersion: '2010-09-09'
Description: MSK Cluster with all properties
Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: !Ref 'SubnetIds'
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: !Ref 'SecurityGroups'
Resources:
  TestCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: ClusterWithAllProperties
      KafkaVersion: 2.2.1
      NumberOfBrokerNodes: 3
      EnhancedMonitoring: PER_BROKER
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: ''
        EncryptionInTransit:
          ClientBroker: PLAINTEXT
          InCluster: false
      Tags:
        - {}
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: TestCluster
          resource_type: AWS::MSK::Cluster
          file_path: msk/msk.yaml
          prancer_unique_id: 59d88415-58b0-43f4-af3a-c08d9074ff2b
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        InstanceType: kafka.m5.large
        SecurityGroups: !Ref 'SecurityGroups'
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 100
        ClientSubnets: !Ref 'SubnetIds'
