AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  domain:
    Type: String
    Description: DNS domain to create a SES email for
    Default: '*'
Resources:
  SslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref 'domain'
      SubjectAlternativeNames:
        - !Sub 'www.${domain}'
      ValidationMethod: EMAIL
      CertificateTransparencyLoggingPreference: DISABLED
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: SslCertificate
          resource_type: AWS::CertificateManager::Certificate
          file_path: acm/acm.yaml
          prancer_unique_id: 1d99cb50-ad87-409b-a069-3daffd2f23b9
