AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  domain:
    Type: String
    Description: DNS domain to create a SES email for
    Default: String<The fully qualified domain name (FQDN), such as www.example.com,
      with which you want to secure an ACM certificate, Do not use asterisk (*)>
Resources:
  SslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref 'domain'
      SubjectAlternativeNames:
        - !Sub 'www.${domain}'
      ValidationMethod: DNS
      CertificateTransparencyLoggingPreference: DISABLED
