AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: MyCustomWorkGroup
      Description: My WorkGroup
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
      Tags:
        - created_timestamp: 1646300948
          last_modified_timestamp: 1646300948
          resource_name: MyAthenaWorkGroup
          resource_type: AWS::Athena::WorkGroup
          file_path: /tmp/tmpxofsolel/Athena/athena.yaml
          prancer_unique_id: 32c3465f-a872-48cd-9693-382a5a9a0d3d
