AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: MyCustomWorkGroup
      Description: My WorkGroup
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: MyAthenaWorkGroup
          resource_type: AWS::Athena::WorkGroup
          file_path: Athena/athena.yaml
          prancer_unique_id: ea587b77-a118-409e-a389-8e5f06c2ba05
