AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This CloudFormation sample template DMSAuroraToS3FullLoadAndOngoingReplication creates
  an Aurora RDS instance and DMS instance in a VPC, and a S3 bucket. The Aurora RDS
  instance is configured as the DMS Source Endpoint and the S3 bucket is configured
  as the DMS Target Endpoint. A DMS task is created and configured to migrate existing
  data and replicate ongoing changes from the source endpoint to the target endpoint.
  You will be billed for the AWS resources used if you create a stack from this template.
Parameters:
  ClientIP:
    Description: >-
      The IP address range that can be used to connect to the RDS instances from your
      local machine. It must be a valid IP CIDR range of the form x.x.x.x/x. Pls get
      your address using checkip.amazonaws.com or whatsmyip.org
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: '0.0.0.0/0'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: It must be a valid IP CIDR range of the form x.x.x.x/x.
      Suggest to enable access to your IP address only. Pls get your address using
      checkip.amazonaws.com or whatsmyip.org.
  ExistsDMSVPCRole:
    Default: N
    Description: If the dms-vpc-role exists in your account, please enter Y, else
      enter N
    Type: String
    MinLength: '1'
    MaxLength: '1'
    AllowedPattern: '[YN]'
    ConstraintDescription: Permitted value is Y or N.
  ExistsDMSCloudwatchRole:
    Default: N
    Description: If the dms-cloudwatch-logs-role exists in your account, please enter
      Y, else enter N
    Type: String
    MinLength: '1'
    MaxLength: '1'
    AllowedPattern: '[YN]'
    ConstraintDescription: Permitted value is Y or N.
Conditions:
  NotExistsDMSVPCRole: !Equals
    - !Ref 'ExistsDMSVPCRole'
    - N
  NotExistsDMSCloudwatchRole: !Equals
    - !Ref 'ExistsDMSCloudwatchRole'
    - N
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref 'AWS::StackName'
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: VPC
          resource_type: AWS::EC2::VPC
          file_path: dms/dms.yaml
          prancer_unique_id: e004e52c-71e7-4f01-bc75-e363368e5550
  DBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      CidrBlock: 10.0.0.0/26
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DBSubnet1
          resource_type: AWS::EC2::Subnet
          file_path: dms/dms.yaml
          prancer_unique_id: 881c8adf-ad06-4176-85b1-35b90c03f9d1
  DBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      CidrBlock: 10.0.0.64/26
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DBSubnet2
          resource_type: AWS::EC2::Subnet
          file_path: dms/dms.yaml
          prancer_unique_id: b27db9ee-c02c-4773-91b0-45d81d977288
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: InternetGateway
          resource_type: AWS::EC2::InternetGateway
          file_path: dms/dms.yaml
          prancer_unique_id: 7ab0849f-5a67-41f0-a028-6905ecb6f36d
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'InternetGateway'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AttachGateway
          resource_type: AWS::EC2::VPCGatewayAttachment
          file_path: dms/dms.yaml
          prancer_unique_id: c4cd4fd5-00e2-4f46-9cc2-dd326c0ab541
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: RouteTable
          resource_type: AWS::EC2::RouteTable
          file_path: dms/dms.yaml
          prancer_unique_id: b3093d4c-0601-46a8-8f17-bd5365ab32ff
  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref 'RouteTable'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: Route
          resource_type: AWS::EC2::Route
          file_path: dms/dms.yaml
          prancer_unique_id: 8b90908a-b070-4ef1-98ca-e32428182005
    DependsOn:
      - AttachGateway
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'DBSubnet1'
      RouteTableId: !Ref 'RouteTable'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: SubnetRouteTableAssociation
          resource_type: AWS::EC2::SubnetRouteTableAssociation
          file_path: dms/dms.yaml
          prancer_unique_id: a463f5cd-6b58-4836-bd95-302c06677d92
  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'DBSubnet2'
      RouteTableId: !Ref 'RouteTable'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: SubnetRouteTableAssociation1
          resource_type: AWS::EC2::SubnetRouteTableAssociation
          file_path: dms/dms.yaml
          prancer_unique_id: 83acfc27-49e0-469a-9282-ef77bf96f7fd
  AuroraDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the Aurora SampleDB DB Instance
      SubnetIds:
        - !Ref 'DBSubnet1'
        - !Ref 'DBSubnet2'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AuroraDBSubnetGroup
          resource_type: AWS::RDS::DBSubnetGroup
          file_path: dms/dms.yaml
          prancer_unique_id: c406be33-91f9-4eea-bb0d-4bada11ddc41
  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Aurora SampleDB DB Instance
      GroupName: Aurora SampleDB Security Group
      VpcId: !Ref 'VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 10.0.0.0/24
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AuroraSecurityGroup
          resource_type: AWS::EC2::SecurityGroup
          file_path: dms/dms.yaml
          prancer_unique_id: 3bddc868-229d-4edf-8b80-ac796654e6b5
  AuroraClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Enables bin_log prerequisites
      Family: aurora5.6
      Parameters:
        binlog_format: ROW
        binlog_checksum: NONE
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AuroraClusterParameterGroup
          resource_type: AWS::RDS::DBClusterParameterGroup
          file_path: dms/dms.yaml
          prancer_unique_id: 4a3e5293-d012-4b9d-9bd6-62df346608c9
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: dms_sample
      DBClusterParameterGroupName: !Ref 'AuroraClusterParameterGroup'
      DBSubnetGroupName: !Ref 'AuroraDBSubnetGroup'
      Engine: aurora
      SnapshotIdentifier: arn:aws:rds:us-east-1:343299325021:cluster-snapshot:dms-sampledb-snapshot
      VpcSecurityGroupIds:
        - !Ref 'AuroraSecurityGroup'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AuroraCluster
          resource_type: AWS::RDS::DBCluster
          file_path: dms/dms.yaml
          prancer_unique_id: ad799ef9-357d-4aa4-a4f4-74f26199f473
  AuroraDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref 'AuroraCluster'
      DBInstanceClass: db.t2.medium
      DBInstanceIdentifier: dms-sample
      DBSubnetGroupName: !Ref 'AuroraDBSubnetGroup'
      Engine: aurora
      MultiAZ: 'false'
      PubliclyAccessible: 'true'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AuroraDB
          resource_type: AWS::RDS::DBInstance
          file_path: dms/dms.yaml
          prancer_unique_id: 122aa012-c504-445e-965e-131376c3c26f
    DependsOn:
      - AuroraCluster
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: S3Bucket
          resource_type: AWS::S3::Bucket
          file_path: dms/dms.yaml
          prancer_unique_id: c0c8ac13-2113-49cb-9709-c73049c31e77
  DMSCloudwatchRole:
    Type: AWS::IAM::Role
    Condition: NotExistsDMSCloudwatchRole
    Properties:
      RoleName: dms-cloudwatch-logs-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole
      Path: /
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DMSCloudwatchRole
          resource_type: AWS::IAM::Role
          file_path: dms/dms.yaml
          prancer_unique_id: bd8cdffd-6933-4e28-8e72-2568a76dc995
  DMSVpcRole:
    Type: AWS::IAM::Role
    Condition: NotExistsDMSVPCRole
    Properties:
      RoleName: dms-vpc-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole
      Path: /
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DMSVpcRole
          resource_type: AWS::IAM::Role
          file_path: dms/dms.yaml
          prancer_unique_id: d725571b-a31f-4e37-a701-ff5a55d28eb2
  S3TargetDMSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dms-s3-target-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3AccessForDMSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !GetAtt 'S3Bucket.Arn'
                  - !Join
                    - ''
                    - - !GetAtt 'S3Bucket.Arn'
                      - /*
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !GetAtt 'S3Bucket.Arn'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: S3TargetDMSRole
          resource_type: AWS::IAM::Role
          file_path: dms/dms.yaml
          prancer_unique_id: c6679c96-002d-40d0-8539-59b3fb86c384
    DependsOn:
      - S3Bucket
  DMSReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupDescription: Subnets available for DMS
      SubnetIds:
        - !Ref 'DBSubnet1'
        - !Ref 'DBSubnet2'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DMSReplicationSubnetGroup
          resource_type: AWS::DMS::ReplicationSubnetGroup
          file_path: dms/dms.yaml
          prancer_unique_id: efc0fef0-edb6-4b0d-bd37-b91585095eca
  DMSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for DMS Instance
      GroupName: DMS Demo Security Group
      VpcId: !Ref 'VPC'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DMSSecurityGroup
          resource_type: AWS::EC2::SecurityGroup
          file_path: dms/dms.yaml
          prancer_unique_id: 36d58e32-915b-4fb2-a922-b5b6272f2a01
  DMSReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      AvailabilityZone: !GetAtt 'DBSubnet1.AvailabilityZone'
      PubliclyAccessible: true
      ReplicationInstanceClass: dms.t2.small
      ReplicationInstanceIdentifier: aurora-s3-repinstance-sampledb
      ReplicationSubnetGroupIdentifier: !Ref 'DMSReplicationSubnetGroup'
      VpcSecurityGroupIds:
        - !Ref 'DMSSecurityGroup'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DMSReplicationInstance
          resource_type: AWS::DMS::ReplicationInstance
          file_path: dms/dms.yaml
          prancer_unique_id: a4ec4b80-fbd9-4189-b0ef-6e5040e1fac8
    DependsOn:
      - DMSReplicationSubnetGroup
      - DMSSecurityGroup
  AuroraSourceEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointType: source
      EngineName: AURORA
      Password: password
      Port: 3306
      ServerName: !GetAtt 'AuroraCluster.Endpoint.Address'
      Username: admin
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: AuroraSourceEndpoint
          resource_type: AWS::DMS::Endpoint
          file_path: dms/dms.yaml
          prancer_unique_id: c369d15b-2289-4af4-8974-e38fec80dcc6
    DependsOn:
      - DMSReplicationInstance
      - AuroraCluster
      - AuroraDB
  S3TargetEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointType: target
      EngineName: S3
      ExtraConnectionAttributes: addColumnName=true
      S3Settings:
        BucketName: !Ref 'S3Bucket'
        ServiceAccessRoleArn: !GetAtt 'S3TargetDMSRole.Arn'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: S3TargetEndpoint
          resource_type: AWS::DMS::Endpoint
          file_path: dms/dms.yaml
          prancer_unique_id: c8921fce-fa0d-40b5-a04e-d79f2f2eceae
    DependsOn:
      - DMSReplicationInstance
      - S3Bucket
      - S3TargetDMSRole
  DMSReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: full-load-and-cdc
      ReplicationInstanceArn: !Ref 'DMSReplicationInstance'
      ReplicationTaskSettings: >-
        { "Logging" : { "EnableLogging" : true, "LogComponents": [ { "Id" : "SOURCE_UNLOAD",
        "Severity" : "LOGGER_SEVERITY_DEFAULT" }, { "Id" : "SOURCE_CAPTURE", "Severity"
        : "LOGGER_SEVERITY_DEFAULT" }, { "Id" : "TARGET_LOAD", "Severity" : "LOGGER_SEVERITY_DEFAULT"
        }, { "Id" : "TARGET_APPLY", "Severity" : "LOGGER_SEVERITY_DEFAULT" } ] } }
      SourceEndpointArn: !Ref 'AuroraSourceEndpoint'
      TableMappings: '{ "rules": [ { "rule-type" : "selection", "rule-id" : "1", "rule-name"
        : "1", "object-locator" : { "schema-name" : "dms_sample", "table-name" : "%"
        }, "rule-action" : "include" } ] }'
      TargetEndpointArn: !Ref 'S3TargetEndpoint'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: DMSReplicationTask
          resource_type: AWS::DMS::ReplicationTask
          file_path: dms/dms.yaml
          prancer_unique_id: 9e50bc4b-b941-48de-86fa-3f036bd23654
    DependsOn:
      - AuroraSourceEndpoint
      - S3TargetEndpoint
      - DMSReplicationInstance
Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
  RegionName:
    Value: !Ref 'AWS::Region'
  S3BucketName:
    Value: !Ref 'S3Bucket'
  AuroraEndpoint:
    Value: !GetAtt 'AuroraCluster.Endpoint.Address'
