AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: CodeDeployApplication
          resource_type: AWS::CodeDeploy::Application
          file_path: codedeploy/codedeploy.yaml
          prancer_unique_id: 46875e2b-061c-4c86-ac90-07c8f8543c7c
