AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Lambda Sample.
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
  LambdaHandlerPath:
    Type: String
    Description: Path of a Lambda Handler.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value: !GetAtt 'LambdaRole.Arn'
    Export:
      Name: !Sub 'LambdaRole'
  LambdaFunctionName:
    Value: !Ref 'LambdaFunction'
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value: !GetAtt 'LambdaFunction.Arn'
    Export:
      Name: !Sub 'LambdaARN-${EnvName}'
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'lambda-role'
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess
      Path: /
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: LambdaRole
          resource_type: AWS::IAM::Role
          file_path: lambda/lambda-sample.yaml
          prancer_unique_id: 2600f5a4-92b9-4c2e-bf33-1b43db9f41b2
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      FunctionName: !Sub 'lambda-function-${EnvName}'
      Description: LambdaFunctioni of nodejs10.x.
      Runtime: nodejs10.x
      Code:
        ZipFile: "exports.handler = function(event, context){\n var sample = sample;"
      Handler: ${LambdaHandlerPath}
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt 'LambdaRole.Arn'
      TracingConfig:
        Mode: PassThrough
      Environment:
        Variables:
          ENV: !Sub '${EnvName}'
          TZ: UTC
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: LambdaFunction
          resource_type: AWS::Lambda::Function
          file_path: lambda/lambda-sample.yaml
          prancer_unique_id: '00164b39-d8dc-465d-bd6d-9386e8204b6d'
  MyEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      SourceAccessConfigurations:
        - Type: BASIC_AUTH
          URI: http://localhost:8000
      EventSourceArn: !Join
        - ''
        - - 'arn:aws:kinesis:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - :stream/
          - !Ref 'KinesisStream'
      FunctionName: !GetAtt 'LambdaFunction.Arn'
      StartingPosition: TRIM_HORIZON
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: MyEventSourceMapping
          resource_type: AWS::Lambda::EventSourceMapping
          file_path: lambda/lambda-sample.yaml
          prancer_unique_id: 9ba6e22d-b8ce-4b3a-b526-a3791f04d029
