AWSTemplateFormatVersion: 2010-09-09
Description: Template for Lambda Sample.
Parameters:
  EnvName:
    Type: String
    Default: 'dev'
    Description: 'Name of an environment. ''dev'', ''staging'', ''prod'' and any name.'
    AllowedPattern: '^.*[^0-9]$'
    ConstraintDescription: Must end with non-numeric character.
  LambdaHandlerPath:
    Type: String
    Default: 'test'
    Description: Path of a Lambda Handler.
    AllowedPattern: '^.*[^0-9]$'
    ConstraintDescription: Must end with non-numeric character.
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value: !GetAtt 
      - LambdaRole
      - Arn
    Export:
      Name: !Sub LambdaRole
  LambdaFunctionName:
    Value: !Ref LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value: !GetAtt 
      - LambdaFunction
      - Arn
    Export:
      Name: !Sub 'LambdaARN-${EnvName}'
Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonKinesisFullAccess'
      Path: /
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub 'lambda-function-${EnvName}'
      Description: LambdaFunctioni of nodejs10.x.
      Runtime: nodejs10.x
      Code:
        ZipFile: |-
          exports.handler = function(event, context){
           var sample = sample;
      Handler: '${LambdaHandlerPath}'
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt 
        - LambdaRole
        - Arn
      TracingConfig:
        Mode: PassThrough
      Environment:
        Variables:
          ENV: !Sub '${EnvName}'
          TZ: UTC
