AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template IAM Roles for Systems Manager | Automation
  Service
Resources:
  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cft_Role1
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: ManagedInstanceRole
        resource_type: AWS::IAM::Role
        file_path: /tmp/tmppo4czohi/iam/iam.yaml
        prancer_unique_id: e2c4edf0-c17b-4af8-b9c4-0d99b52570be
  AssumeDeveloperRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAllUsersToListAccounts
            Effect: Allow
            Action: '*'
            Resource: '*'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: AssumeDeveloperRolePolicy
        resource_type: AWS::IAM::ManagedPolicy
        file_path: /tmp/tmppo4czohi/iam/iam.yaml
        prancer_unique_id: bddf7f17-61a6-4272-999e-1974cffb9219
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Test@1234
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: CFNUser
        resource_type: AWS::IAM::User
        file_path: /tmp/tmppo4czohi/iam/iam.yaml
        prancer_unique_id: a93db9b2-90e6-4fcd-af0c-98e909634fcf
  CFNAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      Policies:
        - PolicyName: myapppolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: CFNAdminGroup
        resource_type: AWS::IAM::Group
        file_path: /tmp/tmppo4czohi/iam/iam.yaml
        prancer_unique_id: 4dbbcc3d-85ac-4813-89db-370bef8730a6
  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'CFNAdminGroup'
      Users: []
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: Users
        resource_type: AWS::IAM::UserToGroupAddition
        file_path: /tmp/tmppo4czohi/iam/iam.yaml
        prancer_unique_id: b9584a3e-a719-43a3-a188-c51041c378b2
