AWSTemplateFormatVersion: 2010-09-09
Description:
  AWS CloudFormation template IAM Roles for Systems Manager | Automation
  Service
Resources:
  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cft_Role1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
      Tags: 
        - Key: prancer_unique_id
          Value: 476f6ca7-8fe7-4a8e-8a8a-e3099d64ce5c
  aws-cloud-test:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-cloud-test
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: dax.amazonaws.com
          Action: sts:AssumeRole
      Tags: 
        - Key: prancer_unique_id
          Value: 	121c7c77-7cfb-4b20-9b81-1f51edbe9ae7
  AssumeDeveloperRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAllUsersToListAccounts
            Effect: Allow
            Action: "*"
            Resource: "*"
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Test@1234
      Tags: 
        - Key: prancer_unique_id
          Value: c3b370c9-a596-416b-bf2c-265a6bd1c056
        - Key: resource_type
          Value: aws::iam::user
  CFNAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      Policies:
        - PolicyName: myapppolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref "CFNAdminGroup"
      Users: []
  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNUsers
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "lambda:*"
              - "cloudformation:Describe*"
              - "cloudformation:List*"
              - "cloudformation:Get*"
              - "iam:PassRole"
            Resource: "*"
            Condition:
              IpAddress:
                aws:SourceIp: 0.0.0.0/0
                aws:username: "test"
      Groups:
        - !Ref CFNAdminGroup
