AWSTemplateFormatVersion: 2010-09-09
Resources:
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      UserName: testuser
      LoginProfile:
        Password: Test@1234
      Tags: 
        - Key: prancer_unique_id
          Value: c3b370c9-a596-416b-bf2c-265a6bd1c056
        - Key: resource_type
          Value: aws::iam::user