AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: !Ref 'VpcId'
Resources:
  MyNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VpcId'
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: MyNACL
          resource_type: AWS::EC2::NetworkAcl
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 1ae54ace-da3c-4232-a7e2-e1c635ddc043
  EC2NetworkAclentryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 1
      Egress: false
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: EC2NetworkAclentryIngress1
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 2bb50996-d250-45d3-a501-3bcb621247a2
  EC2NetworkAclentryIngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 2
      Egress: false
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: EC2NetworkAclentryIngress2
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 96a8eeb7-a034-472f-812b-22b4913728fc
  EC2NetworkAclentryIngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 3
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: EC2NetworkAclentryIngress3
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: d595d74e-1c5b-4cd3-9617-9e392e74bcba
  EC2NetworkAclentryEngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 4
      Egress: true
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: EC2NetworkAclentryEngress1
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: d92a770f-e227-49a7-b78b-69652443ce4a
  EC2NetworkAclentryEngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 5
      Egress: true
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: EC2NetworkAclentryEngress2
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 4c4eed40-5e5a-4eca-8fb1-36a37d111552
  EC2NetworkAclentryEngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 6
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646367757
          last_modified_timestamp: 1646367757
          resource_name: EC2NetworkAclentryEngress3
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: ac4e618d-f5e7-42a4-972c-d582585a147d
