AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: !Ref 'VpcId'
Resources:
  MyNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VpcId'
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: MyNACL
          resource_type: AWS::EC2::NetworkAcl
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 2f09096a-4414-4089-b1c0-2bdaa0c495e8
  EC2NetworkAclentryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 1
      Egress: false
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: EC2NetworkAclentryIngress1
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 187ee428-1e1a-4281-9e3e-f400ef9ee4a5
  EC2NetworkAclentryIngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 2
      Egress: false
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: EC2NetworkAclentryIngress2
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: '0df99bca-1eb7-4550-9f20-2e921abfb33a'
  EC2NetworkAclentryIngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 3
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: EC2NetworkAclentryIngress3
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: ac6638f3-cb21-4560-9329-60d172ae2509
  EC2NetworkAclentryEngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 4
      Egress: true
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: EC2NetworkAclentryEngress1
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 6ce4ed73-3932-4fad-a015-6bb14741f6c5
  EC2NetworkAclentryEngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 5
      Egress: true
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: EC2NetworkAclentryEngress2
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: f839c966-04ae-44b6-addb-984a1db9daab
  EC2NetworkAclentryEngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 6
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: EC2NetworkAclentryEngress3
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 864a7212-c6c7-4e0c-9602-59cf5181ebdd
