AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: !Ref 'VpcId'
Resources:
  MyNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VpcId'
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: MyNACL
          resource_type: AWS::EC2::NetworkAcl
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: '00b10027-fc93-4f82-b3b7-2ec5b782a6e0'
  EC2NetworkAclentryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 1
      Egress: false
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: EC2NetworkAclentryIngress1
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 479e2216-7f3f-4795-8093-d4bc9d430547
  EC2NetworkAclentryIngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 2
      Egress: false
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: EC2NetworkAclentryIngress2
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: c214e52b-7b15-41a5-83ab-e57f65d3e06d
  EC2NetworkAclentryIngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 3
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: EC2NetworkAclentryIngress3
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 789a340f-4f25-4db6-97cd-08e07f0ce4b2
  EC2NetworkAclentryEngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 4
      Egress: true
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: EC2NetworkAclentryEngress1
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 848579c0-6aa4-4467-b52f-5a512586c06d
  EC2NetworkAclentryEngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 5
      Egress: true
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: EC2NetworkAclentryEngress2
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 25f5f9ac-017d-426c-8a84-5c5a2dbbb994
  EC2NetworkAclentryEngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 6
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646301343
          resource_name: EC2NetworkAclentryEngress3
          resource_type: AWS::EC2::NetworkAclEntry
          file_path: NetworkACL/networkackentry.yaml
          prancer_unique_id: 3324a8d7-b51e-456a-80bf-e644e58acc11
