AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: !Ref 'VpcId'
Resources:
  MyNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VpcId'
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: MyNACL
        - Key: resource_type
          Value: AWS::EC2::NetworkAcl
        - Key: prancer_unique_id
          Value: 7732bcfe-874d-4a03-8b2e-94a356537559
  EC2NetworkAclentryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 1
      Egress: false
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: EC2NetworkAclentryIngress1
        - Key: resource_type
          Value: AWS::EC2::NetworkAclEntry
        - Key: prancer_unique_id
          Value: f3d171d6-770d-44f2-90ff-e1a8c62736e4
  EC2NetworkAclentryIngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 2
      Egress: false
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: EC2NetworkAclentryIngress2
        - Key: resource_type
          Value: AWS::EC2::NetworkAclEntry
        - Key: prancer_unique_id
          Value: f278444c-98e1-4476-8e9a-3689107c6d79
  EC2NetworkAclentryIngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 3
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: EC2NetworkAclentryIngress3
        - Key: resource_type
          Value: AWS::EC2::NetworkAclEntry
        - Key: prancer_unique_id
          Value: 49442e6e-9a13-4427-9de8-693d49d46624
  EC2NetworkAclentryEngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 4
      Egress: true
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: EC2NetworkAclentryEngress1
        - Key: resource_type
          Value: AWS::EC2::NetworkAclEntry
        - Key: prancer_unique_id
          Value: d087934b-4ccc-49ca-8e93-ccb1b6bb95e3
  EC2NetworkAclentryEngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 5
      Egress: true
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: EC2NetworkAclentryEngress2
        - Key: resource_type
          Value: AWS::EC2::NetworkAclEntry
        - Key: prancer_unique_id
          Value: 203d32ce-3c45-42e4-a1ae-50ccceb381e8
  EC2NetworkAclentryEngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 6
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
      Tags:
        - Key: created_timestamp
          Value: 1646386202
        - Key: last_modified_timestamp
          Value: 1646386202
        - Key: resource_name
          Value: EC2NetworkAclentryEngress3
        - Key: resource_type
          Value: AWS::EC2::NetworkAclEntry
        - Key: prancer_unique_id
          Value: c4ef7474-9925-44d9-a2c8-82efb4a09d95
