AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: !Ref 'VpcId'
Resources:
  MyNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VpcId'
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: MyNACL
        resource_type: AWS::EC2::NetworkAcl
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: 28ceaa21-19b8-4ce0-a5f4-4c107b091b3e
  EC2NetworkAclentryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 1
      Egress: false
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: EC2NetworkAclentryIngress1
        resource_type: AWS::EC2::NetworkAclEntry
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: cf765455-8516-494b-a837-0e6921845dd1
  EC2NetworkAclentryIngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 2
      Egress: false
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: EC2NetworkAclentryIngress2
        resource_type: AWS::EC2::NetworkAclEntry
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: 43ec6686-bb24-4d24-a551-e3bd611135e1
  EC2NetworkAclentryIngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 3
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: EC2NetworkAclentryIngress3
        resource_type: AWS::EC2::NetworkAclEntry
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: 4430ee69-3731-4c54-a5fd-0d4b30f2500b
  EC2NetworkAclentryEngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 4
      Egress: true
      Protocol: 1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: EC2NetworkAclentryEngress1
        resource_type: AWS::EC2::NetworkAclEntry
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: 5453481c-6cdf-4724-908d-996d6557456c
  EC2NetworkAclentryEngress2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 5
      Egress: true
      Protocol: 1
      RuleAction: allow
      Ipv6CidrBlock: ::/0
      PortRange:
        From: 22
        To: 22
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: EC2NetworkAclentryEngress2
        resource_type: AWS::EC2::NetworkAclEntry
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: e688cfec-8786-4f4e-83bc-3340af5026db
  EC2NetworkAclentryEngress3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Icmp:
        Code: -1
        Type: -1
      NetworkAclId: !Ref 'MyNACL'
      RuleNumber: 6
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 22
        To: 22
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: EC2NetworkAclentryEngress3
        resource_type: AWS::EC2::NetworkAclEntry
        file_path: /tmp/tmppo4czohi/NetworkACL/networkackentry.yaml
        prancer_unique_id: '007e500c-d628-4710-80d0-86c967eba4b1'
