AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyVPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed
      to
    Default: !Ref 'MyVPC'
Resources:
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: true
      VpcId: !Ref 'MyVPC'
      CidrBlock: 172.31.48.0/20
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: mySubnet
          resource_type: AWS::EC2::Subnet
          file_path: /tmp/tmpxofsolel/vpc/vpc.yaml
          prancer_unique_id: cc3a847f-a5cd-41d7-a794-742a131a9649
  VPCEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: VPCEndpointService
          resource_type: AWS::EC2::VPCEndpointService
          file_path: /tmp/tmpxofsolel/vpc/vpc.yaml
          prancer_unique_id: dc321acf-0b98-4fa5-860b-d0acf2cc5f23
