AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyVPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed
      to
    Default: !Ref 'MyVPC'
Resources:
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: true
      VpcId: !Ref 'MyVPC'
      CidrBlock: 172.31.48.0/20
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: mySubnet
          resource_type: AWS::EC2::Subnet
          file_path: vpc/vpc.yaml
          prancer_unique_id: 8cee5a76-f0b8-4af4-a316-44e86a2c5012
  VPCEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: VPCEndpointService
          resource_type: AWS::EC2::VPCEndpointService
          file_path: vpc/vpc.yaml
          prancer_unique_id: ddfc4986-0822-40f9-9aa0-2582f696e812
