AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDBInstance:
    Type: AWS::DocDB::DBCluster
    Properties:
      BackupRetentionPeriod: 8
      DBClusterIdentifier: sample-cluster
      DBSubnetGroupName: default
      MasterUsername: Root
      MasterUserPassword: Root1234
      Port: '27017'
      StorageEncrypted: false
      Tags:
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646302584
          resource_name: myDBInstance
          resource_type: AWS::DocDB::DBCluster
          file_path: doc_db/docdb.yaml
          prancer_unique_id: 45b005c9-690f-41df-90bb-5d7629b0dffa
  myDBInstanceParameter:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties:
      Description: description
      Family: docdb3.6
      Name: sampleParameterGroup
      Parameters:
        audit_logs: disabled
        tls: disabled
        ttl_monitor: disabled
      Tags:
        - Key: String
          Value: String
        - created_timestamp: 1646301343
          last_modified_timestamp: 1646302584
          resource_name: myDBInstanceParameter
          resource_type: AWS::DocDB::DBClusterParameterGroup
          file_path: doc_db/docdb.yaml
          prancer_unique_id: 1fde27f2-7f5d-42f7-a22e-9cc3f8da9b12
