AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDBInstance:
    Type: AWS::DocDB::DBCluster
    Properties:
      BackupRetentionPeriod: 8
      DBClusterIdentifier: sample-cluster
      DBSubnetGroupName: default
      MasterUsername: Root
      MasterUserPassword: Root1234
      Port: '27017'
      StorageEncrypted: false
      Tags:
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: myDBInstance
          resource_type: AWS::DocDB::DBCluster
          file_path: doc_db/docdb.yaml
          prancer_unique_id: 880ede27-cf1d-4c52-a929-04b9546f71e8
  myDBInstanceParameter:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties:
      Description: description
      Family: docdb3.6
      Name: sampleParameterGroup
      Parameters:
        audit_logs: disabled
        tls: disabled
        ttl_monitor: disabled
      Tags:
        - Key: String
          Value: String
        - created_timestamp: 1646384788
          last_modified_timestamp: 1646384788
          resource_name: myDBInstanceParameter
          resource_type: AWS::DocDB::DBClusterParameterGroup
          file_path: doc_db/docdb.yaml
          prancer_unique_id: 9079a76b-c64e-4b8a-a873-f7de17c01e35
