AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDBInstance:
    Type: AWS::DocDB::DBCluster
    Properties:
      BackupRetentionPeriod: 8
      DBClusterIdentifier: sample-cluster
      DBSubnetGroupName: default
      MasterUsername: Root
      MasterUserPassword: Root1234
      Port: '27017'
      StorageEncrypted: false
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: myDBInstance
        resource_type: AWS::DocDB::DBCluster
        file_path: /tmp/tmppo4czohi/doc_db/docdb.yaml
        prancer_unique_id: b4f1425a-6474-402e-b4b1-ec77b63ef826
  myDBInstanceParameter:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties:
      Description: description
      Family: docdb3.6
      Name: sampleParameterGroup
      Parameters:
        audit_logs: disabled
        tls: disabled
        ttl_monitor: disabled
      Tags:
        - Key: String
          Value: String
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: myDBInstanceParameter
        resource_type: AWS::DocDB::DBClusterParameterGroup
        file_path: /tmp/tmppo4czohi/doc_db/docdb.yaml
        prancer_unique_id: e261f453-1ad8-4e42-9b23-454e5deabb2e
