AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDBInstance:
    Type: AWS::DocDB::DBCluster
    Properties:
      BackupRetentionPeriod: 8
      DBClusterIdentifier: sample-cluster
      DBSubnetGroupName: default
      MasterUsername: Root
      MasterUserPassword: Root1234
      Port: '27017'
      StorageEncrypted: false
      Tags:
        - created_timestamp: 1646368505
          last_modified_timestamp: 1646368505
          resource_name: myDBInstance
          resource_type: AWS::DocDB::DBCluster
          file_path: doc_db/docdb.yaml
          prancer_unique_id: 41437876-a244-4ac1-91b1-a54a40c2298a
  myDBInstanceParameter:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties:
      Description: description
      Family: docdb3.6
      Name: sampleParameterGroup
      Parameters:
        audit_logs: disabled
        tls: disabled
        ttl_monitor: disabled
      Tags:
        - Key: String
          Value: String
        - created_timestamp: 1646368505
          last_modified_timestamp: 1646368505
          resource_name: myDBInstanceParameter
          resource_type: AWS::DocDB::DBClusterParameterGroup
          file_path: doc_db/docdb.yaml
          prancer_unique_id: da424a06-4f33-4825-ad7d-ff64905c8e7f
