AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z8VLZEXAMPLE
      Name: test.example.com
      ResourceRecords:
        - 192.0.2.99
      TTL: 900
      Type: AAAA
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: myDNSRecord
          resource_type: AWS::Route53::RecordSet
          file_path: /tmp/tmpxofsolel/route53/route53.yaml
          prancer_unique_id: 8c159cee-bde7-4511-b76a-0fb58b799826
  myDNSOne:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: test
      Comment: Weighted RR for my frontends.
      RecordSets:
        - Name: mysite.example.com.
          Type: CNAME
          TTL: '900'
          SetIdentifier: Frontend One
          Weight: '4'
          ResourceRecords:
            - example-ec2.amazonaws.com
        - Name: mysite.example.com.
          Type: CNAME
          TTL: '900'
          SetIdentifier: Frontend Two
          Weight: '6'
          ResourceRecords:
            - example-ec2-larger.amazonaws.com
      Tags:
        - created_timestamp: 1646300947
          last_modified_timestamp: 1646300947
          resource_name: myDNSOne
          resource_type: AWS::Route53::RecordSetGroup
          file_path: /tmp/tmpxofsolel/route53/route53.yaml
          prancer_unique_id: 3c310901-aed5-445c-87e1-37177b225a92
