AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestAppsync:
    Type: AWS::AppSync::GraphQLApi
      Properties:
        Name: graphQlApiName
        AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
        UserPoolConfig:
          UserPoolId:
            Ref: userPoolId
          AwsRegion:
            Ref: userPoolAwsRegion
          DefaultAction:
            Ref: defaultAction
  MyWebACLAssociationForAppsync:
      Type: "AWS::WAFRegional::WebACLAssociation"
      Properties:
        ResourceArn:
          Ref: TestAppsync
