AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      Encrypted: false
      PubliclyAccessible: true
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: Root12345
      NodeType: ds2.xlarge
      ClusterType: single-node
      ClusterSubnetGroupName: String<The name of a cluster subnet group to be associated
        with this cluster.>
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: true
