AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      Encrypted: false
      PubliclyAccessible: true
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: Root12345
      NodeType: ds2.xlarge
      ClusterType: single-node
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: RedshiftCluster
        resource_type: AWS::Redshift::Cluster
        file_path: /tmp/tmppo4czohi/redshift/redshift.yaml
        prancer_unique_id: 328842b7-6a94-423d-94c4-70a89a0b76a7
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: true
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: RedshiftClusterParameterGroup
        resource_type: AWS::Redshift::ClusterParameterGroup
        file_path: /tmp/tmppo4czohi/redshift/redshift.yaml
        prancer_unique_id: 5974bcd4-4c3a-463a-8b07-80fcf35bac66
