AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      Encrypted: false
      PubliclyAccessible: true
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: Root12345
      NodeType: ds2.xlarge
      ClusterType: single-node
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: RedshiftCluster
          resource_type: AWS::Redshift::Cluster
          file_path: redshift/redshift.yaml
          prancer_unique_id: 4ad0b1d5-5eac-49bd-8c7f-3eacc22b75cb
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: true
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: RedshiftClusterParameterGroup
          resource_type: AWS::Redshift::ClusterParameterGroup
          file_path: redshift/redshift.yaml
          prancer_unique_id: c57fa326-6b3d-4de4-a3f1-140b96fbfec3
