AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      Encrypted: false
      PubliclyAccessible: true
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: Root12345
      NodeType: ds2.xlarge
      ClusterType: single-node
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: RedshiftCluster
          resource_type: AWS::Redshift::Cluster
          file_path: redshift/redshift.yaml
          prancer_unique_id: 11aec31b-e92c-470a-8783-e1783a52301d
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: true
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301344
          resource_name: RedshiftClusterParameterGroup
          resource_type: AWS::Redshift::ClusterParameterGroup
          file_path: redshift/redshift.yaml
          prancer_unique_id: '08d4862a-e1ce-47c6-9b0a-653e9793b677'
