AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      Encrypted: false
      PubliclyAccessible: true
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: Root12345
      NodeType: ds2.xlarge
      ClusterType: single-node
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: RedshiftCluster
          resource_type: AWS::Redshift::Cluster
          file_path: redshift/redshift.yaml
          prancer_unique_id: c8147ed0-7abd-48a1-9230-05c10b6a58bf
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: true
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: RedshiftClusterParameterGroup
          resource_type: AWS::Redshift::ClusterParameterGroup
          file_path: redshift/redshift.yaml
          prancer_unique_id: 92939628-ab51-497f-947b-20b5d1397257
