AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      Encrypted: false
      PubliclyAccessible: true
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: Root12345
      NodeType: ds2.xlarge
      ClusterType: single-node
      Tags:
        - created_timestamp: 1646367738
          last_modified_timestamp: 1646367738
          resource_name: RedshiftCluster
          resource_type: AWS::Redshift::Cluster
          file_path: redshift/redshift.yaml
          prancer_unique_id: 7e7e34a2-582f-4d17-b555-1780b598607a
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: true
      Tags:
        - created_timestamp: 1646367738
          last_modified_timestamp: 1646367738
          resource_name: RedshiftClusterParameterGroup
          resource_type: AWS::Redshift::ClusterParameterGroup
          file_path: redshift/redshift.yaml
          prancer_unique_id: 2f6da881-011f-43a4-87b6-2a67379bf2a1
