AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Load Balancer
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed
      to
  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed
      to
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  S3BUCKET:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: String<The Amazon Resource Name (ARN) of the AWS Identity and Access
          Management (IAM) role that Amazon S3 assumes when replicating objects.>
        Rules:
          - DeleteMarkerReplication:
              Status: 'String<Specifies whether the rule is enabled. Allowed values:
                Disabled | Enabled>'
              Destination:
                AccessControlTranslation:
                  Owner: String<Specifies the replica ownership. For default and valid
                    values, see https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTreplication.html
                    in the Amazon S3 API Reference.>
                Account: String<Destination bucket owner account ID.>
                Bucket: String<The Amazon Resource Name (ARN) of the bucket where
                  you want Amazon S3 to store the results.>
                EncryptionConfiguration:
                  ReplicaKmsKeyID: String<Specifies the ID (Key ARN or Alias ARN)
                    of the customer managed AWS KMS key stored in AWS Key Management
                    Service (KMS) for the destination bucket.>
                Metrics:
                  EventThreshold:
                    Minutes: Integer<Contains an integer specifying time in minutes.>
                  Status: 'String<Specifies whether the replication metrics are enabled.
                    Allowed values: Disabled | Enabled>'
                ReplicationTime:
                  Status: 'String<Specifies whether the replication time is enabled.
                    Allowed values: Disabled | Enabled>'
                  Time:
                    Minutes: Integer<Contains an integer specifying time in minutes.>
                StorageClass: String<The storage class to use when replicating objects,
                  such as S3 Standard or reduced redundancy.>
              Filter:
                And:
                  Prefix: String<An object key name prefix that identifies the subset
                    of objects to which the rule applies.>
                  TagFilters:
                    - Key: String<The tag key.>
                      Value: String<The tag value.>
                Prefix: String<An object key name prefix that identifies the subset
                  of objects to which the rule applies.>
                TagFilter:
                  - Key: String<The tag key.>
                    Value: String<The tag value.>
              Id: >-
                String<A unique identifier for the rule. The maximum value is 255
                characters. If you don't specify a value, AWS CloudFormation generates
                a random ID. When using a V2 replication configuration this property
                is capitalized as 'ID'.>
              Prefix: >-
                String<An object key name prefix that identifies the object or objects
                to which the rule applies. The maximum prefix length is 1,024 characters.
                To include all objects in a bucket, specify an empty string.>
              Priority: >-
                Integer<The priority indicates which rule has precedence whenever
                two or more replication rules conflict. Amazon S3 will attempt to
                replicate objects according to all replication rules. However, if
                there are two or more rules with the same destination bucket, then
                objects will be replicated according to the rule with the highest
                priority. The higher the number, the higher the priority.>
              SourceSelectionCriteria:
                ReplicaModifications:
                  Status: 'String<Specifies whether Amazon S3 replicates modifications
                    on replicas. Allowed values: Enabled | Disabled>'
                SseKmsEncryptedObjects:
                  Status: 'String<Specifies whether Amazon S3 replicates objects created
                    with server-side encryption using an AWS KMS key stored in AWS
                    Key Management Service. Allowed values: Disabled | Enabled>'
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AccessLoggingPolicy:
        Enabled: false
        S3BucketName: !Ref 'S3BUCKET'
      CrossZone: false
      Subnets: !Ref 'Subnets'
      ConnectionDrainingPolicy:
        Enabled: false
      Listeners:
        - InstancePort: '80'
          InstanceProtocol: HTTP
          LoadBalancerPort: '443'
          Protocol: HTTPS
          PolicyNames:
            - My-SSLNegotiation-Policy
          SSLCertificateId: arn:aws:iam::123456789012:server-certificate/my-server-certificate
      Policies:
        - PolicyName: My-SSLNegotiation-Policy
          PolicyType: SSLNegotiationPolicyType
          Attributes:
            - Name: DHE-RSA-AES128-SHA
              Value: 'true'
            - Name: DHE-DSS-AES128-SHA
              Value: 'true'
            - Name: CAMELLIA128-SHA
              Value: 'true'
            - Name: EDH-RSA-DES-CBC3-SHA
              Value: 'true'
            - Name: DES-CBC3-SHA
              Value: 'true'
            - Name: ECDHE-RSA-RC4-SHA
              Value: 'true'
            - Name: RC4-SHA
              Value: 'true'
            - Name: ECDHE-ECDSA-RC4-SHA
              Value: 'true'
            - Name: DHE-DSS-AES256-GCM-SHA384
              Value: 'true'
            - Name: DHE-RSA-AES256-GCM-SHA384
              Value: 'true'
            - Name: DHE-RSA-AES256-SHA256
              Value: 'true'
            - Name: DHE-DSS-AES256-SHA256
              Value: 'true'
            - Name: DHE-RSA-AES256-SHA
              Value: 'true'
            - Name: DHE-DSS-AES256-SHA
              Value: 'true'
            - Name: DHE-RSA-CAMELLIA256-SHA
              Value: 'true'
            - Name: DHE-DSS-CAMELLIA256-SHA
              Value: 'true'
            - Name: CAMELLIA256-SHA
              Value: 'true'
            - Name: EDH-DSS-DES-CBC3-SHA
              Value: 'true'
            - Name: DHE-DSS-AES128-GCM-SHA256
              Value: 'true'
            - Name: DHE-RSA-AES128-GCM-SHA256
              Value: 'true'
            - Name: DHE-RSA-AES128-SHA256
              Value: 'true'
            - Name: DHE-DSS-AES128-SHA256
              Value: 'true'
            - Name: DHE-RSA-CAMELLIA128-SHA
              Value: 'true'
            - Name: DHE-DSS-CAMELLIA128-SHA
              Value: 'true'
            - Name: ADH-AES128-GCM-SHA256
              Value: 'true'
            - Name: ADH-AES128-SHA
              Value: 'true'
            - Name: ADH-AES128-SHA256
              Value: 'true'
            - Name: ADH-AES256-GCM-SHA384
              Value: 'true'
            - Name: ADH-AES256-SHA
              Value: 'true'
            - Name: ADH-AES256-SHA256
              Value: 'true'
            - Name: ADH-CAMELLIA128-SHA
              Value: 'true'
            - Name: ADH-CAMELLIA256-SHA
              Value: 'true'
            - Name: ADH-DES-CBC3-SHA
              Value: 'true'
            - Name: ADH-DES-CBC-SHA
              Value: 'true'
            - Name: ADH-RC4-MD5
              Value: 'true'
            - Name: ADH-SEED-SHA
              Value: 'true'
            - Name: DES-CBC-SHA
              Value: 'true'
            - Name: DHE-DSS-SEED-SHA
              Value: 'true'
            - Name: DHE-RSA-SEED-SHA
              Value: 'true'
            - Name: EDH-DSS-DES-CBC-SHA
              Value: 'true'
            - Name: EDH-RSA-DES-CBC-SHA
              Value: 'true'
            - Name: IDEA-CBC-SHA
              Value: 'true'
            - Name: RC4-MD5
              Value: 'true'
            - Name: SEED-SHA
              Value: 'true'
            - Name: DES-CBC3-MD5
              Value: 'true'
            - Name: DES-CBC-MD5
              Value: 'true'
            - Name: RC2-CBC-MD5
              Value: 'true'
            - Name: PSK-AES256-CBC-SHA
              Value: 'true'
            - Name: PSK-3DES-EDE-CBC-SHA
              Value: 'true'
            - Name: KRB5-DES-CBC3-SHA
              Value: 'true'
            - Name: KRB5-DES-CBC3-MD5
              Value: 'true'
            - Name: PSK-AES128-CBC-SHA
              Value: 'true'
            - Name: PSK-RC4-SHA
              Value: 'true'
            - Name: KRB5-RC4-SHA
              Value: 'true'
            - Name: KRB5-RC4-MD5
              Value: 'true'
            - Name: KRB5-DES-CBC-SHA
              Value: 'true'
            - Name: KRB5-DES-CBC-MD5
              Value: 'true'
            - Name: EXP-EDH-RSA-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-EDH-DSS-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-ADH-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-RC2-CBC-MD5
              Value: 'true'
            - Name: EXP-KRB5-RC2-CBC-SHA
              Value: 'true'
            - Name: EXP-KRB5-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-KRB5-RC2-CBC-MD5
              Value: 'true'
            - Name: EXP-KRB5-DES-CBC-MD5
              Value: 'true'
            - Name: EXP-ADH-RC4-MD5
              Value: 'true'
            - Name: EXP-RC4-MD5
              Value: 'true'
            - Name: EXP-KRB5-RC4-SHA
              Value: 'true'
            - Name: EXP-KRB5-RC4-MD5
              Value: 'true'
            - Name: Protocol-SSLv3
              Value: 'true'
            - Name: Protocol-TLSv1
              Value: 'true'
            - Name: Protocol-TLSv1.1
              Value: 'true'
  MyLoadBalancerV2:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: false
      Subnets: !Ref 'Subnets'
  DummyTargetGroupPublic:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - drop-1
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref 'VPC'
  PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - MyLoadBalancerV2
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'DummyTargetGroupPublic'
          Type: forward
      LoadBalancerArn: !Ref 'MyLoadBalancerV2'
      Port: 80
      Protocol: HTTP
