AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Load Balancer
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed
      to
    Default: !Ref 'VPC'
  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed
      to
    Type: List<AWS::EC2::Subnet::Id>
    Default: !Ref 'Subnets'
Resources:
  S3BUCKET:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: S3BUCKET
        resource_type: AWS::S3::Bucket
        file_path: /tmp/tmppo4czohi/elb/elb.yaml
        prancer_unique_id: 371df96d-7881-4bb2-8285-44c80669bd5d
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AccessLoggingPolicy:
        Enabled: false
        S3BucketName: !Ref 'S3BUCKET'
      CrossZone: false
      Subnets: !Ref 'Subnets'
      ConnectionDrainingPolicy:
        Enabled: false
      Listeners:
        - InstancePort: '80'
          InstanceProtocol: HTTP
          LoadBalancerPort: '443'
          Protocol: HTTPS
          PolicyNames:
            - My-SSLNegotiation-Policy
          SSLCertificateId: arn:aws:iam::123456789012:server-certificate/my-server-certificate
      Policies:
        - PolicyName: My-SSLNegotiation-Policy
          PolicyType: SSLNegotiationPolicyType
          Attributes:
            - Name: DHE-RSA-AES128-SHA
              Value: 'true'
            - Name: DHE-DSS-AES128-SHA
              Value: 'true'
            - Name: CAMELLIA128-SHA
              Value: 'true'
            - Name: EDH-RSA-DES-CBC3-SHA
              Value: 'true'
            - Name: DES-CBC3-SHA
              Value: 'true'
            - Name: ECDHE-RSA-RC4-SHA
              Value: 'true'
            - Name: RC4-SHA
              Value: 'true'
            - Name: ECDHE-ECDSA-RC4-SHA
              Value: 'true'
            - Name: DHE-DSS-AES256-GCM-SHA384
              Value: 'true'
            - Name: DHE-RSA-AES256-GCM-SHA384
              Value: 'true'
            - Name: DHE-RSA-AES256-SHA256
              Value: 'true'
            - Name: DHE-DSS-AES256-SHA256
              Value: 'true'
            - Name: DHE-RSA-AES256-SHA
              Value: 'true'
            - Name: DHE-DSS-AES256-SHA
              Value: 'true'
            - Name: DHE-RSA-CAMELLIA256-SHA
              Value: 'true'
            - Name: DHE-DSS-CAMELLIA256-SHA
              Value: 'true'
            - Name: CAMELLIA256-SHA
              Value: 'true'
            - Name: EDH-DSS-DES-CBC3-SHA
              Value: 'true'
            - Name: DHE-DSS-AES128-GCM-SHA256
              Value: 'true'
            - Name: DHE-RSA-AES128-GCM-SHA256
              Value: 'true'
            - Name: DHE-RSA-AES128-SHA256
              Value: 'true'
            - Name: DHE-DSS-AES128-SHA256
              Value: 'true'
            - Name: DHE-RSA-CAMELLIA128-SHA
              Value: 'true'
            - Name: DHE-DSS-CAMELLIA128-SHA
              Value: 'true'
            - Name: ADH-AES128-GCM-SHA256
              Value: 'true'
            - Name: ADH-AES128-SHA
              Value: 'true'
            - Name: ADH-AES128-SHA256
              Value: 'true'
            - Name: ADH-AES256-GCM-SHA384
              Value: 'true'
            - Name: ADH-AES256-SHA
              Value: 'true'
            - Name: ADH-AES256-SHA256
              Value: 'true'
            - Name: ADH-CAMELLIA128-SHA
              Value: 'true'
            - Name: ADH-CAMELLIA256-SHA
              Value: 'true'
            - Name: ADH-DES-CBC3-SHA
              Value: 'true'
            - Name: ADH-DES-CBC-SHA
              Value: 'true'
            - Name: ADH-RC4-MD5
              Value: 'true'
            - Name: ADH-SEED-SHA
              Value: 'true'
            - Name: DES-CBC-SHA
              Value: 'true'
            - Name: DHE-DSS-SEED-SHA
              Value: 'true'
            - Name: DHE-RSA-SEED-SHA
              Value: 'true'
            - Name: EDH-DSS-DES-CBC-SHA
              Value: 'true'
            - Name: EDH-RSA-DES-CBC-SHA
              Value: 'true'
            - Name: IDEA-CBC-SHA
              Value: 'true'
            - Name: RC4-MD5
              Value: 'true'
            - Name: SEED-SHA
              Value: 'true'
            - Name: DES-CBC3-MD5
              Value: 'true'
            - Name: DES-CBC-MD5
              Value: 'true'
            - Name: RC2-CBC-MD5
              Value: 'true'
            - Name: PSK-AES256-CBC-SHA
              Value: 'true'
            - Name: PSK-3DES-EDE-CBC-SHA
              Value: 'true'
            - Name: KRB5-DES-CBC3-SHA
              Value: 'true'
            - Name: KRB5-DES-CBC3-MD5
              Value: 'true'
            - Name: PSK-AES128-CBC-SHA
              Value: 'true'
            - Name: PSK-RC4-SHA
              Value: 'true'
            - Name: KRB5-RC4-SHA
              Value: 'true'
            - Name: KRB5-RC4-MD5
              Value: 'true'
            - Name: KRB5-DES-CBC-SHA
              Value: 'true'
            - Name: KRB5-DES-CBC-MD5
              Value: 'true'
            - Name: EXP-EDH-RSA-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-EDH-DSS-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-ADH-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-RC2-CBC-MD5
              Value: 'true'
            - Name: EXP-KRB5-RC2-CBC-SHA
              Value: 'true'
            - Name: EXP-KRB5-DES-CBC-SHA
              Value: 'true'
            - Name: EXP-KRB5-RC2-CBC-MD5
              Value: 'true'
            - Name: EXP-KRB5-DES-CBC-MD5
              Value: 'true'
            - Name: EXP-ADH-RC4-MD5
              Value: 'true'
            - Name: EXP-RC4-MD5
              Value: 'true'
            - Name: EXP-KRB5-RC4-SHA
              Value: 'true'
            - Name: EXP-KRB5-RC4-MD5
              Value: 'true'
            - Name: Protocol-SSLv3
              Value: 'true'
            - Name: Protocol-TLSv1
              Value: 'true'
            - Name: Protocol-TLSv1.1
              Value: 'true'
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: MyLoadBalancer
        resource_type: AWS::ElasticLoadBalancing::LoadBalancer
        file_path: /tmp/tmppo4czohi/elb/elb.yaml
        prancer_unique_id: 18dfceb1-f3db-4dd3-8831-2689d402ff0b
  MyLoadBalancerV2:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: false
      Subnets: !Ref 'Subnets'
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: MyLoadBalancerV2
        resource_type: AWS::ElasticLoadBalancingV2::LoadBalancer
        file_path: /tmp/tmppo4czohi/elb/elb.yaml
        prancer_unique_id: eb043d4b-4359-4240-ab8f-d3aed1829628
  DummyTargetGroupPublic:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - drop-1
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref 'VPC'
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: DummyTargetGroupPublic
        resource_type: AWS::ElasticLoadBalancingV2::TargetGroup
        file_path: /tmp/tmppo4czohi/elb/elb.yaml
        prancer_unique_id: f84a0c45-95e7-48f1-b86b-f774d7f9325a
  PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - MyLoadBalancerV2
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'DummyTargetGroupPublic'
          Type: redirect
          RedirectConfig:
            Protocol: http
        - TargetGroupArn: !Ref 'DummyTargetGroupPublic'
          Type: authenticate-cognito
      LoadBalancerArn: !Ref 'MyLoadBalancerV2'
      Port: 80
      Protocol: HTTP
    Tags:
      - created_timestamp: 1646300564
        last_modified_timestamp: 1646300564
        resource_name: PublicLoadBalancerListener
        resource_type: AWS::ElasticLoadBalancingV2::Listener
        file_path: /tmp/tmppo4czohi/elb/elb.yaml
        prancer_unique_id: dfb9d5f6-bac9-43ff-a6e5-72627e948565
