AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecretForAppA
      Description: This secret has a dynamically generated secret password.
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: password
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: AppA
      KMSKeyId: String<The ARN, key ID, or alias of the AWS KMS key that Secrets Manager
        uses to encrypt the secret value in the secret.>
