AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: TestVPC
          resource_type: AWS::EC2::VPC
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 36bc669a-5ca1-46bf-a0a7-f695321bad72
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: TestSubnet01
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: '006df513-0f56-4f52-8a97-89f1c7a8a17c'
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: TestSubnet02
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 7201814f-587b-4e45-9ce4-a6689b7ea59a
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: SecretsManagerVPCEndpoint
          resource_type: AWS::EC2::VPCEndpoint
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 36476701-68c5-4d14-9e6e-9cc20bad450b
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: MyRDSInstanceRotationSecret
          resource_type: AWS::SecretsManager::Secret
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: bf8620b8-4520-446e-946b-39050771eb58
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: MyDBInstance
          resource_type: AWS::RDS::DBInstance
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 3a87a4e3-cc79-4044-b72d-e4a842dd7d3b
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: MyDBSubnetGroup
          resource_type: AWS::RDS::DBSubnetGroup
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: b7212620-80ee-4009-bad2-7994955a1fdc
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: SecretRDSInstanceAttachment
          resource_type: AWS::SecretsManager::SecretTargetAttachment
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: b1f92ae8-8134-49d7-b3f3-f0468c67a241
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
      Tags:
        - created_timestamp: 1646384789
          last_modified_timestamp: 1646384789
          resource_name: MySecretRotationSchedule
          resource_type: AWS::SecretsManager::RotationSchedule
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: d5ce1978-a3ac-4baa-b7a8-7af37eb61434
