AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: TestVPC
        resource_type: AWS::EC2::VPC
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 75308a3b-bcb9-47cc-bd7f-01e6715ac10e
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: TestSubnet01
        resource_type: AWS::EC2::Subnet
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 8bdfec08-81e8-4966-9408-60a63b7481d5
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: TestSubnet02
        resource_type: AWS::EC2::Subnet
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 411c060b-60b7-417f-bc27-d2b0a082d540
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: SecretsManagerVPCEndpoint
        resource_type: AWS::EC2::VPCEndpoint
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 9bb94364-6a1b-43b8-8cb6-4f6704f05f84
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: MyRDSInstanceRotationSecret
        resource_type: AWS::SecretsManager::Secret
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: bfe34b2a-5e8c-423e-a43c-cfb5fcab2ea9
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: MyDBInstance
        resource_type: AWS::RDS::DBInstance
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 9ddea026-907d-4645-872b-f3ac19885a93
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: MyDBSubnetGroup
        resource_type: AWS::RDS::DBSubnetGroup
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 361de330-8e78-47f7-927a-ebc3b72c2e15
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: SecretRDSInstanceAttachment
        resource_type: AWS::SecretsManager::SecretTargetAttachment
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: ef36f69f-4993-4ac8-a70c-561a7a52f7e1
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
    Tags:
      - created_timestamp: 1646300565
        last_modified_timestamp: 1646300565
        resource_name: MySecretRotationSchedule
        resource_type: AWS::SecretsManager::RotationSchedule
        file_path: /tmp/tmppo4czohi/secret_manager/secret_manager.yaml
        prancer_unique_id: 50d7daf2-51f3-484e-8c32-f376aaef0845
