AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: TestVPC
        - Key: resource_type
          Value: AWS::EC2::VPC
        - Key: prancer_unique_id
          Value: dac4a03a-c0f5-4f10-b22f-4ff498f765f6
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: TestSubnet01
        - Key: resource_type
          Value: AWS::EC2::Subnet
        - Key: prancer_unique_id
          Value: aa5265ec-c4f4-4983-b781-a486df5f688e
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: TestSubnet02
        - Key: resource_type
          Value: AWS::EC2::Subnet
        - Key: prancer_unique_id
          Value: e1a85bc8-7ce3-4228-a71a-2f38c9699585
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: SecretsManagerVPCEndpoint
        - Key: resource_type
          Value: AWS::EC2::VPCEndpoint
        - Key: prancer_unique_id
          Value: f20e8cc8-146e-4489-aa81-f65284110503
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: MyRDSInstanceRotationSecret
        - Key: resource_type
          Value: AWS::SecretsManager::Secret
        - Key: prancer_unique_id
          Value: 6b4ab728-15ad-46be-930b-5cc6cb7a9c12
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: MyDBInstance
        - Key: resource_type
          Value: AWS::RDS::DBInstance
        - Key: prancer_unique_id
          Value: b0c955a9-8cac-4de0-9952-80f73c2e016a
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: MyDBSubnetGroup
        - Key: resource_type
          Value: AWS::RDS::DBSubnetGroup
        - Key: prancer_unique_id
          Value: 694d2c78-1eef-45fa-ad8e-86155ffa7f70
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: SecretRDSInstanceAttachment
        - Key: resource_type
          Value: AWS::SecretsManager::SecretTargetAttachment
        - Key: prancer_unique_id
          Value: 60a703fe-3b76-4f4f-aaf2-1787fd5bc798
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
      Tags:
        - Key: created_timestamp
          Value: 1646386203
        - Key: last_modified_timestamp
          Value: 1646386203
        - Key: resource_name
          Value: MySecretRotationSchedule
        - Key: resource_type
          Value: AWS::SecretsManager::RotationSchedule
        - Key: prancer_unique_id
          Value: 5ffc10ff-0348-4ba1-b847-dac4a9696d5f
