AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: TestVPC
          resource_type: AWS::EC2::VPC
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: dd3b2972-7db3-485d-b33f-5eda728a07e6
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: TestSubnet01
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 4a4bff2a-1646-4dbc-8ddc-a6e0ad7dc6e9
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: TestSubnet02
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 516f99b3-343f-4719-bac8-d7f78e7e463d
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: SecretsManagerVPCEndpoint
          resource_type: AWS::EC2::VPCEndpoint
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: b77f46af-4272-480c-8ff9-1a7c32629f25
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: MyRDSInstanceRotationSecret
          resource_type: AWS::SecretsManager::Secret
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: e4c859c2-cdbb-4831-91a6-2e56cc4e3953
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: MyDBInstance
          resource_type: AWS::RDS::DBInstance
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 13872e0b-907c-411b-b0be-dd2dd56c0735
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: MyDBSubnetGroup
          resource_type: AWS::RDS::DBSubnetGroup
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: a081afe5-5ea7-4801-99b2-45e60663eacd
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: SecretRDSInstanceAttachment
          resource_type: AWS::SecretsManager::SecretTargetAttachment
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 986e587b-72fe-4997-a212-1f4fed05b943
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
      Tags:
        - created_timestamp: 1646367758
          last_modified_timestamp: 1646367758
          resource_name: MySecretRotationSchedule
          resource_type: AWS::SecretsManager::RotationSchedule
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 8e502d52-2469-483b-9516-e0f43267a326
