AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: TestVPC
          resource_type: AWS::EC2::VPC
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: fd1bdde0-7d1d-418b-95c9-2c7d8818d251
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: TestSubnet01
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: ee55b465-2090-4986-8f8d-56ffed8fd3a8
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: TestSubnet02
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 65e93323-d255-4668-9390-afcc76e2f0cf
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: SecretsManagerVPCEndpoint
          resource_type: AWS::EC2::VPCEndpoint
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 58d031e7-4216-4965-bd3e-539fe0e518c0
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: MyRDSInstanceRotationSecret
          resource_type: AWS::SecretsManager::Secret
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: '0346d416-8d81-4486-a2aa-46e1f023b01e'
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: MyDBInstance
          resource_type: AWS::RDS::DBInstance
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 626af984-4ea0-4b9b-906f-4de2ca00ca31
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: MyDBSubnetGroup
          resource_type: AWS::RDS::DBSubnetGroup
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 78dc4c2a-b09d-4060-a461-d3fed381b188
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: SecretRDSInstanceAttachment
          resource_type: AWS::SecretsManager::SecretTargetAttachment
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 49841d44-f7b6-435f-b5f5-cf00b7735ee8
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
      Tags:
        - created_timestamp: 1646367737
          last_modified_timestamp: 1646367737
          resource_name: MySecretRotationSchedule
          resource_type: AWS::SecretsManager::RotationSchedule
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: dd79ac14-9712-4c5d-954a-43df9f7aeab0
