AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: TestVPC
          resource_type: AWS::EC2::VPC
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 53cc2bb6-f7ae-4265-a99e-bed48262d0ab
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: TestSubnet01
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 31629e60-25a6-4b43-b133-f84a4c3cb69b
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: TestSubnet02
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: f37c7487-2076-47d3-8654-3a5819e659b1
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: SecretsManagerVPCEndpoint
          resource_type: AWS::EC2::VPCEndpoint
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 15fbf3d5-4e31-47f7-97c3-b00b360eed31
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: MyRDSInstanceRotationSecret
          resource_type: AWS::SecretsManager::Secret
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 1be0a03d-0bdc-4dec-b815-3457d627c11c
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: MyDBInstance
          resource_type: AWS::RDS::DBInstance
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 3abb2d99-6cb6-4654-9686-dd0190bdc77c
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: MyDBSubnetGroup
          resource_type: AWS::RDS::DBSubnetGroup
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 86631021-b5e9-496e-b13b-446183484706
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: SecretRDSInstanceAttachment
          resource_type: AWS::SecretsManager::SecretTargetAttachment
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: '0daf5df3-96bf-430f-9397-e427b89b9450'
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
      Tags:
        - created_timestamp: 1646368506
          last_modified_timestamp: 1646368506
          resource_name: MySecretRotationSchedule
          resource_type: AWS::SecretsManager::RotationSchedule
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: ffbe3070-c0df-4b7e-a442-2591f2fa25de
