AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: TestVPC
          resource_type: AWS::EC2::VPC
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: e90fd16d-91ab-4c22-b80c-a7086d8fff2e
  TestSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: TestSubnet01
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 6097d28b-00c3-4630-9a16-7be968ac9771
  TestSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: TestSubnet02
          resource_type: AWS::EC2::Subnet
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: ab9a5281-b8eb-480a-af51-1dc592358c2c
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      SecurityGroupIds:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: true
      VpcId: !Ref 'TestVPC'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: SecretsManagerVPCEndpoint
          resource_type: AWS::EC2::VPCEndpoint
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 6ad7df18-bf02-4634-9f3c-6c80745cbbe6
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: MyApp
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: MyRDSInstanceRotationSecret
          resource_type: AWS::SecretsManager::Secret
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: e9abe163-9f9f-4a97-b57c-136dcc593c8c
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secret:${MyRDSInstanceRotationSecret}::password}}'
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !GetAtt 'TestVPC.DefaultSecurityGroup'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: MyDBInstance
          resource_type: AWS::RDS::DBInstance
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: c4ceb43d-e39f-4a05-881b-222834eb7803
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - !Ref 'TestSubnet01'
        - !Ref 'TestSubnet02'
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: MyDBSubnetGroup
          resource_type: AWS::RDS::DBSubnetGroup
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 276cb290-1867-4ea5-ad36-75ad8c6e2079
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      TargetId: !Ref 'MyDBInstance'
      TargetType: AWS::RDS::DBInstance
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: SecretRDSInstanceAttachment
          resource_type: AWS::SecretsManager::SecretTargetAttachment
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 10d5ae67-8d66-4aba-9407-677a1bdbe54e
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId: !Ref 'MyRDSInstanceRotationSecret'
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds: !GetAtt 'TestVPC.DefaultSecurityGroup'
      RotationRules:
        AutomaticallyAfterDays: 30
      Tags:
        - created_timestamp: 1646301344
          last_modified_timestamp: 1646301466
          resource_name: MySecretRotationSchedule
          resource_type: AWS::SecretsManager::RotationSchedule
          file_path: secret_manager/secret_manager.yaml
          prancer_unique_id: 35f781d3-76b8-4473-a50b-8d80548309ee
